### ISSUE TITLE
Templates 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#104]

**Comment by ZarshaB** [comment]
1>> **Verify Account:**
It is having logo download option please remove this.
![image](https://user-images.githubusercontent.com/35685146/36963807-8094cb6c-2076-11e8-81ff-25e17c4c54d2.png)

2>> Button's text is "Verify My Account" instead of "Verify Account".
![image](https://user-images.githubusercontent.com/35685146/36964689-439023d0-2079-11e8-9fb5-e16d1b475318.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36964708-551d0596-2079-11e8-927d-4eb117a01e53.png)

3>> Please remove space between Cheers and Team WelaDela. 
![image](https://user-images.githubusercontent.com/35685146/36964766-83b5406c-2079-11e8-8fe0-00ba54caa008.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36964791-956f6710-2079-11e8-83a8-fc1cddd85712.png)


4>> Please also remove these lines from logo.
![image](https://user-images.githubusercontent.com/35685146/36964831-ab471b6e-2079-11e8-8ad8-a69b5ac2e563.png)

**Comment by ZarshaB** [comment]
5>> Cheers should be small in size and Team WelaDela should be large in font size.
![image](https://user-images.githubusercontent.com/35685146/36964934-e9fa40c0-2079-11e8-8b8c-70862d7c0e96.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36964952-f819dbde-2079-11e8-9afd-2b1d5b141270.png)

**Comment by ZarshaB** [comment]
6>> Also make whole text bold for template.
![image](https://user-images.githubusercontent.com/35685146/36965030-35f8887e-207a-11e8-8667-121ed9c00daf.png)

**Comment by ZarshaB** [comment]
**Winner Template**
7>> Exclamation mark is missing.
![image](https://user-images.githubusercontent.com/35685146/36966186-bf200322-207d-11e8-9e9d-19760affa328.png)

**Comment by ZarshaB** [comment]
8>> On Outlook it is appearing like this but when I view in full size then it becomes okay.
![image](https://user-images.githubusercontent.com/35685146/36967663-25df7d46-2082-11e8-82a3-a43c223f70c5.png)

**Comment by ZarshaB** [comment]
9>> **Refund Ticket:**
Ticket number is not appearing.
![image](https://user-images.githubusercontent.com/35685146/36967739-633d5b9a-2082-11e8-9b66-a4d59720e6df.png)

**Comment by ZarshaB** [comment]
11>> **Ticket Transfer**
Ad title is not here. 
![image](https://user-images.githubusercontent.com/35685146/36969031-283cc586-2086-11e8-98b2-fef8de906a3a.png)

12>> Good Luck would be little larger in size and also it's spacing is not same.
![image](https://user-images.githubusercontent.com/35685146/36969076-4a0d1094-2086-11e8-8ebc-d5a82035a18f.png)

**Comment by ZarshaB** [comment]
13>> Please remove spaces between these lines. 
![image](https://user-images.githubusercontent.com/35685146/37036509-b6a1687c-2171-11e8-91b3-56662bff2601.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/37036532-c2aa7032-2171-11e8-9829-9be6d895a6a3.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing. 

11>> Ticket Transfer
12>> Good Luck would be little larger in size and also it's spacing is not same.
13>> Please remove spaces between these lines

**Comment by ZarshaB** [comment]
13>> Fixed
11 >> Not Fixed
12>> Good Luck size is now okay but spacing is not same.

**Comment by ZarshaB** [comment]
14>> Order Summary Template:
Spacing is not equal of both "Date" and "Order Id". And also full stop is at a distance from weldela.com.
![image](https://user-images.githubusercontent.com/35685146/37146408-6c41c284-22e5-11e8-9ba1-0c5905073357.png)

**Comment by ZarshaB** [comment]
15>> **Buy Now:**
Please remove this space a little.
![image](https://user-images.githubusercontent.com/35685146/37203171-9fe8ead0-23ae-11e8-8f40-bf3da5542f38.png)

**Comment by ZarshaB** [comment]
16>> **Welcome email.**
Please underline this.
![image](https://user-images.githubusercontent.com/35685146/37203214-be468028-23ae-11e8-8420-548e459f0211.png)

**Comment by ZarshaB** [comment]
17>> Welcome Email.
Price is in decimals. Button text color is changed.
![image](https://user-images.githubusercontent.com/35685146/37277448-6f323be4-2606-11e8-8927-a553a2493129.png)

**Comment by ZarshaB** [comment]
18>> Refund Template.
No image. No link and no ticket number.
![image](https://user-images.githubusercontent.com/35685146/37278833-ca2b5f72-260a-11e8-8065-2802e7381ef7.png)

**Comment by ZarshaB** [comment]
19>> Transfer Template:
No title, tickets sold and price.
![image](https://user-images.githubusercontent.com/35685146/37281707-c01f8b76-2613-11e8-9eb5-f60440b66749.png)

**Comment by ZarshaB** [comment]
20>> **Welcome Email Outlook:**
![image](https://user-images.githubusercontent.com/35685146/37398478-7f550380-27a0-11e8-9328-edb76fffbce5.png)
![image](https://user-images.githubusercontent.com/35685146/37398505-966e5f80-27a0-11e8-9ed5-d08fadceab38.png)

**Comment by ZarshaB** [comment]
22>> For Transfer, Refund, Sold, Winner (Outlook)
Footer is overlapping and also not centre aligned.
![image](https://user-images.githubusercontent.com/35685146/37398716-38d14c56-27a1-11e8-9298-1c78e4abfe19.png)

**Comment by ZarshaB** [comment]
23>> **Ticket Transfer outlook:**
Car's title , ticket sold and ticket's price is not aligned.
![image](https://user-images.githubusercontent.com/35685146/37398846-98768ff4-27a1-11e8-82b8-40758b638a6e.png)

**Comment by ZarshaB** [comment]
24>> **Order Summary Outlook**
![image](https://user-images.githubusercontent.com/35685146/37398874-ada681fe-27a1-11e8-8dcd-aa72157de53e.png)

**Comment by ZarshaB** [comment]
25>> **All templates of gmail:**
Footer does not have same spacing.
![image](https://user-images.githubusercontent.com/35685146/37399079-6acea2a2-27a2-11e8-9031-b1e579499bd9.png)

**Comment by ZarshaB** [comment]
26>> **gmail welcome email.**
logo is not correct.
![image](https://user-images.githubusercontent.com/35685146/37399107-7c5f5c0a-27a2-11e8-9bc6-bc7584e66754.png)

**Comment by ZarshaB** [comment]
27>> Order Summary gmail.
![image](https://user-images.githubusercontent.com/35685146/37399231-ef2309d0-27a2-11e8-9296-adbec4115cb1.png)

**Comment by ZarshaB** [comment]
28>> Order Summary:
Order Id and Date is having extra text. Remove space for dot after weladela.com
![image](https://user-images.githubusercontent.com/35685146/37399349-48aa3ab4-27a3-11e8-8ae2-d7b3a1562176.png)

**Comment by ZarshaB** [comment]
29>> Refund:
Ticket sold is appearing in minus.
![image](https://user-images.githubusercontent.com/35685146/37399587-de834e4a-27a3-11e8-836f-01b8ac656571.png)

**Comment by ZarshaB** [comment]
**15th March 2018**
**Outlook**
Ticket Transfer:
![image](https://user-images.githubusercontent.com/35685146/37451874-c70d8fc6-2854-11e8-8bf5-9b3e7429f736.png)

Ticket Refund:
Negative sign for Ticket Sold. Ticket Price is in decimal.
![image](https://user-images.githubusercontent.com/35685146/37451958-05f9553a-2855-11e8-8ee1-6c8577d323e7.png)

Order Summary:
![image](https://user-images.githubusercontent.com/35685146/37451977-1684b5d4-2855-11e8-8b6b-950537503235.png)

Welcome Email:
![image](https://user-images.githubusercontent.com/35685146/37452001-25e1c1b6-2855-11e8-90d6-8b7c87af10f8.png)

**Comment by ZarshaB** [comment]
**15th March 2018
Gmail**
Transfer Template
![image](https://user-images.githubusercontent.com/35685146/37452521-acc15eac-2856-11e8-9e20-92f02875bad0.png)

Order Summary
![image](https://user-images.githubusercontent.com/35685146/37452543-b98358fc-2856-11e8-8ec3-f5a348dde7ce.png)

Refund Template
![image](https://user-images.githubusercontent.com/35685146/37452564-c6007f92-2856-11e8-8211-d9cd8bcfed08.png)

Welcome Email
![image](https://user-images.githubusercontent.com/35685146/37452590-dad6e9e2-2856-11e8-984c-1bac3a8b07ab.png)

**Comment by ZarshaB** [comment]
**Updated Report:**
Gmail Welcome Email Template mobile:
![image](https://user-images.githubusercontent.com/35685146/37465603-68d779d4-287d-11e8-92a5-cfcefb0b966d.png)

Website:
![image](https://user-images.githubusercontent.com/35685146/37465671-9bde7b8e-287d-11e8-8194-da8a34fc3191.png)

It should be like this(centre aligned and bold like this) to maintain consistency. Also cheers look different than other templates.
![image](https://user-images.githubusercontent.com/35685146/37465705-b1368864-287d-11e8-9880-940cf9866475.png)
![image](https://user-images.githubusercontent.com/35685146/37465738-d09e6b9a-287d-11e8-9880-a934c7796a7b.png)

**Comment by ZarshaB** [comment]
Refund Email:
If title is long then button disappears. Also button text should be "Buy Ticket".
![image](https://user-images.githubusercontent.com/35685146/37465874-2a9520bc-287e-11e8-8a93-ff793d019c76.png)

**Comment by ZarshaB** [comment]
For Order Summary seeing same.

**Comment by ZarshaB** [comment]
Welcome Gmail:
It is not @ 
![image](https://user-images.githubusercontent.com/35685146/37468641-5e00b19e-2885-11e8-8fba-61663198191d.png)

**Comment by ZarshaB** [comment]
Welcome Outlook Mobile:
![image](https://user-images.githubusercontent.com/35685146/37469378-ef525516-2886-11e8-93c9-5be472ee4d94.png)

**Comment by ZarshaB** [comment]
Gmail:
Order Summary Email is going out of table.

**Comment by ZarshaB** [comment]
4>> Ticket Refund Gmail:
![image](https://user-images.githubusercontent.com/35685146/37470504-7b99e424-2889-11e8-825f-c2728217ef72.png)
![image](https://user-images.githubusercontent.com/35685146/37470529-89e46496-2889-11e8-82b0-36443f644477.png)

**Comment by ZarshaB** [comment]
5>> Ticket Transfer outlook:
Thora sa alignment issue
![image](https://user-images.githubusercontent.com/35685146/37471044-b49acc06-288a-11e8-8b84-2c306bae4362.png)

**Comment by ZarshaB** [comment]
6>> Remove:
Name is not appearing.
![image](https://user-images.githubusercontent.com/35685146/37471291-3c55fa26-288b-11e8-8030-04e90b7b0440.png)

**Comment by ZarshaB** [comment]
7>> Customer Enquiry:
Change it to Email please.
![image](https://user-images.githubusercontent.com/35685146/37472124-20882baa-288d-11e8-8df0-3b1868677dfe.png)

**Comment by ZarshaB** [comment]
8>> Alignment issue:
![image](https://user-images.githubusercontent.com/35685146/37472205-55e8847a-288d-11e8-9ccd-672039e39088.png)

**Comment by ZarshaB** [comment]
9>> @sammiullah ye sb pehle fill the ab fill q nh hain? :/
![image](https://user-images.githubusercontent.com/35685146/37472408-d8529ef0-288d-11e8-87d9-9c63d394f53a.png)

**Comment by ZarshaB** [comment]
1>> Welcome Email gmail:
Mobile:
![image](https://user-images.githubusercontent.com/35685146/37468721-90db06c8-2885-11e8-8858-d1176beb8eec.png)

**Comment by sammiullah** [comment]
7>> Customer Enquiry: fixed

**Comment by ZarshaB** [comment]
6>> Templates logo place is disturbed.
7>> Refund Template:
![image](https://user-images.githubusercontent.com/35685146/37510036-99b28992-291b-11e8-843d-1c592aa44502.png)
![image](https://user-images.githubusercontent.com/35685146/37510049-a333e0ce-291b-11e8-9b75-8bcae80227c5.png)

**Comment by ZarshaB** [comment]
9>> Transfer Template:
![image](https://user-images.githubusercontent.com/35685146/37511176-b23327c0-291f-11e8-8355-9a09a0ad54c4.png)

**Comment by ZarshaB** [comment]
2>> Welcome Email:
It should not be underlined.
![image](https://user-images.githubusercontent.com/35685146/37514056-a9bc18b4-2928-11e8-97c4-71cf082c2d8e.png)
