### ISSUE TITLE
Android Application Issues

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#115]

**Comment by ZarshaB** [comment]
1>> Prices will not be in decimal.
![image](https://user-images.githubusercontent.com/35685146/37510139-f519ac70-291b-11e8-8be7-d59d283b1725.png)

**Comment by ZarshaB** [comment]
2>> Please change the font of app.

**Comment by ZarshaB** [comment]
3>> No menu bar at below of "More" page.
![image](https://user-images.githubusercontent.com/35685146/37510185-2491751e-291c-11e8-97db-e15701e08d4f.png)

**Comment by ZarshaB** [comment]
4>> Pop up is not having orange outline.
![image](https://user-images.githubusercontent.com/35685146/37510314-7aa70842-291c-11e8-99c3-4025b4e4e893.png)

**Comment by ZarshaB** [comment]
5>> Messages are not correct.
If I click on any option where login is required it should display message:
"Please Login/Register to continue!!!"
![image](https://user-images.githubusercontent.com/35685146/37510378-b03ceb2a-291c-11e8-95a7-0a3160f52fdf.png)

**Comment by ZarshaB** [comment]
6>> Complete email is not appearing.
![image](https://user-images.githubusercontent.com/35685146/37510404-c539e21c-291c-11e8-8ecc-cc9df465fd26.png)

**Comment by ZarshaB** [comment]
7>> Profile picture should not remain save after logout.

**Comment by ZarshaB** [comment]
8>> Page background for "How it works" is different when it is clicked from Menu and from Main page.
![image](https://user-images.githubusercontent.com/35685146/37510600-840b6198-291d-11e8-819a-bef85e77983a.png)

**Comment by ZarshaB** [comment]
6>> This message should be:
"We're here to help. Password reset link has been sent to your email address zarshabatool@gmail.com."
![image](https://user-images.githubusercontent.com/35685146/37510648-b7b3c9fe-291d-11e8-8fb3-f905d2ceacfe.png)

**Comment by ZarshaB** [comment]
10>> It does not highlight field red as it is in template.

Template:
![image](https://user-images.githubusercontent.com/35685146/37512149-14c3ebec-2923-11e8-99ed-9b947437028e.png)

**Comment by ZarshaB** [comment]
11>> After login it should move to this screen.
![image](https://user-images.githubusercontent.com/35685146/37512845-06b44be4-2925-11e8-8529-830c65ac0381.png)

**Comment by ZarshaB** [comment]
11>> When the customer installs and opens the app for first time, then it should ask for permission to send notifications, location etc.

**Comment by ZarshaB** [comment]
12>> So while browsing on different pages of app, when a signed in customer clicks homepage in navbar at the bottom, he'll be routed to view cars homepage and when a signed out customer or first time user clicks the homepage button, he will be routed to the page with pictures at the back and four buttons.

**Comment by ZarshaB** [comment]
13>> When a logged-in customer signs out, he should get a sign out message as per the content and then should be routed back to view cars page. 
**Sign Out message:**
OK. You’ve been logged out. 
Until next time, stay awesome and come back soon!!!

**Comment by ZarshaB** [comment]
14>> Other than the "Go Back Arrow" button, the customer should be able to go back to previous screens or previous page by swiping by his thumb. Please refer to dubizzle app for functionality.

**Comment by ZarshaB** [comment]
15>> Please change the spelling of "My Favourites" to "My Favorites".
![image](https://user-images.githubusercontent.com/35685146/37516163-0ffb6598-292f-11e8-8fce-2fca84b9e3a0.png)

**Comment by ZarshaB** [comment]
16>> This message should be:
Oops!!! Something went wrong. 
Please enter a valid e-mail address.
![image](https://user-images.githubusercontent.com/35685146/37516810-35c084b4-2931-11e8-958f-488a0f954456.png)

**Comment by zohaibqadir** [comment]
1>> Prices will not be in decimal. 
  Fixed

**Comment by zohaibqadir** [comment]
2>> Please change the font of app.
 @Aawaiza  please provide the new assets..

**Comment by zohaibqadir** [comment]
3>> No menu bar at below of "More" page.
 This is default drawer of android and occupies the full width, already discussed with sir Tanzeel

**Comment by zohaibqadir** [comment]
4>> Pop up is not having orange outline.
Fixed

**Comment by zohaibqadir** [comment]
5>> Messages are not correct.
FIXED

**Comment by zohaibqadir** [comment]
6>> Complete email is not appearing.
it depends upon screen size and default behavior of android, moreover I have increase the width of all EditTexts as requested

**Comment by zohaibqadir** [comment]
7>> Profile picture should not remain save after logout.
FIXED

**Comment by zohaibqadir** [comment]
8>> Page background for "How it works" is different when it is clicked from Menu and from Main page.
FIXED

**Comment by zohaibqadir** [comment]
10>> It does not highlight field red as it is in template.
FIXED

**Comment by zohaibqadir** [comment]
11>> When the customer installs and opens the app for first time, then it should ask for permission to send notifications, location etc.
We are taking only those permissions that are required and taking on that screen in which it is required

**Comment by zohaibqadir** [comment]
13>> When a logged-in customer signs out, he should get a sign out message as per the content and then should be routed back to view cars page.
FIXED

**Comment by zohaibqadir** [comment]
14>> Other than the "Go Back Arrow" button, the customer should be able to go back to previous screens or previous page by swiping by his thumb. Please refer to dubizzle app for functionality.
Dubizzle is also working same as Weladela is working... thumb swiping is working on search activity in dubizzle but we haven't any search activity

**Comment by zohaibqadir** [comment]
15>> Please change the spelling of "My Favourites" to "My Favorites".
FIXED

**Comment by zohaibqadir** [comment]
16>> This message should be
FIXED

**Comment by ZarshaB** [comment]
**Not Fixed:**

4>> Whole pop up is not orange.
![image](https://user-images.githubusercontent.com/35685146/37590413-0cd318f4-2b8a-11e8-9e05-89491230c469.png)

10>> It only highlight one field and not the password field.
![image](https://user-images.githubusercontent.com/35685146/37590494-3e48f5a2-2b8a-11e8-8089-eca8174f5437.png)

**Comment by ZarshaB** [comment]
17>> Message is not complete:
![image](https://user-images.githubusercontent.com/35685146/37591313-f0034d7c-2b8c-11e8-9eb5-eed2a08d824e.png)

**Comment by ZarshaB** [comment]
18>> Font size is not same.
![image](https://user-images.githubusercontent.com/35685146/37591379-2afd8ff0-2b8d-11e8-866f-27f467382378.png)

**Comment by ZarshaB** [comment]
19>> It should display message:
Minimum 6 characters required."
![image](https://user-images.githubusercontent.com/35685146/37591418-53c7ea20-2b8d-11e8-9b0e-7d5240f1e9a3.png)

**Comment by ZarshaB** [comment]
20>> Emirates Id should have same pattern as it is in website.

**Comment by ZarshaB** [comment]
21>> Calendar format should be DD/MM/YYYY on Register page.

**Comment by zohaibqadir** [comment]
All Highlighted issues have been fixedl.. Please test

**Comment by ZarshaB** [comment]
22>> Please make it "Male" and "Female".
![image](https://user-images.githubusercontent.com/35685146/37602628-8d85e0ac-2bae-11e8-9de4-c143b3b94922.png)

**Comment by zohaibqadir** [comment]
@asifjans  please see the issue 23

**Comment by ZarshaB** [comment]
24>> When I click on "Favorites" icon without login then it displays me wrong message and also takes me to site's login/register page. Also shows two headers.
![image](https://user-images.githubusercontent.com/35685146/37603245-fe16f026-2baf-11e8-80ea-de45993882ec.png)
![image](https://user-images.githubusercontent.com/35685146/37603267-04e480a8-2bb0-11e8-8445-a6dfb1adeaf4.png)

**Comment by ZarshaB** [comment]
25>> It is not saving/ updating my profile picture.

**Comment by ZarshaB** [comment]
26>> When I click on "Buy Ticket" without login then it displays wrong message. Please change it to "Ooops something went wrong.. Please Login/Register to continue."
![image](https://user-images.githubusercontent.com/35685146/37605058-34d79a30-2bb4-11e8-9b80-abbe05a11bd4.png)

**Comment by ZarshaB** [comment]
27>> Please make the error message as "Email already exists." instead if "Email already exist."

**Comment by ZarshaB** [comment]
28>> Please change this message to:
Minimum 6 characters required.
![image](https://user-images.githubusercontent.com/35685146/37641316-1676fb76-2c3b-11e8-8265-55b028ec349b.png)

**Comment by ZarshaB** [comment]
29>> Please make  these message of wrong password and invalid login as:
"Oops!!! Something went wrong.
Please enter correct Username and Password

Forgot Password?"

![image](https://user-images.githubusercontent.com/35685146/37641971-685259a2-2c3d-11e8-9d82-fe99edd5fdae.png)

**Comment by ZarshaB** [comment]
30>> Also text is overlapping with cross icon.
![image](https://user-images.githubusercontent.com/35685146/37642317-7c4dad3e-2c3e-11e8-984e-8faf70fdf5e2.png)

**Comment by ZarshaB** [comment]
31>> It is allowing to enter alphabets.
![image](https://user-images.githubusercontent.com/35685146/37642380-b73ce306-2c3e-11e8-9ae8-33502a26001b.png)

**Comment by ZarshaB** [comment]
32>> It is redirecting me to this page if WiFi is off.
![image](https://user-images.githubusercontent.com/35685146/37642522-2c69f164-2c3f-11e8-9e1e-76e0181fb63a.png)

**Comment by ZarshaB** [comment]
33>> It ask permissions every time I start app. :octocat:

**Comment by ZarshaB** [comment]
34>> When Home is selected then it would be filled icon as it is in template.
![image](https://user-images.githubusercontent.com/35685146/37651295-7afa67ae-2c59-11e8-8629-451a8c723139.png)

**Comment by shayanr262** [comment]
35>> On Car Detail page, when click on Buy Ticket button the item should be added to Cart.

**Comment by ZarshaB** [comment]
**Not Fixed:**
12
20>> It should give error if user does not fill all dashes.
25>> Not saving my profile.

**Comment by ZarshaB** [comment]
Need to discuss above points( Including dp) with Sir. Other issues are fixed.

**Comment by zohaibqadir** [comment]
Issue 31 and 32 have been fixed

**Comment by zohaibqadir** [comment]
DID you check issue 31 in latest APK?

**Comment by ZarshaB** [comment]
1>> Please change it to "My Favorites".
![image](https://user-images.githubusercontent.com/35685146/37958318-a263e34a-31c9-11e8-9acd-b62ad5cfa6be.png)

**Comment by ZarshaB** [comment]
Login with facebook functionality.

**Comment by ZarshaB** [comment]
1>> There should be fb button.

**Comment by ZarshaB** [comment]
2>> Change the icon for push notification with WlaDela's logo.

**Comment by ZarshaB** [comment]
3>> Loading icon is appearing black.
