### ISSUE TITLE
Feedback - Mobile

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#141]

**Comment by ZarshaB** [comment]
1>> Pages are taking way too much time to load. Any action that I perform, the page gets stuck and takes forever to load especially the payment page.

**Comment by ZarshaB** [comment]
2>> The font is not the same as website in banner. The headings have way too much of spacing. Additionally it is over lapping the search button. Please refer to picture attached.

**Comment by ZarshaB** [comment]
10>> Login with facebook button is very blur.

**Comment by ZarshaB** [comment]
11>> Plce your Ad page
Can all four headings (General Specification, Images and Mulkiya/Ownership Document) be aligned in one line? See if alignment in one line is not effecting the layout and looks nice. If it creates a hotchpotch, then let it be the way it is.
![image](https://user-images.githubusercontent.com/35685146/38189361-42347200-3679-11e8-95a5-f433753db341.png)

**Comment by ZarshaB** [comment]
12>> When I added the car in my favorites, the orange heart is not appearing when I view the list. However, it is there when I do the detailed view of the car.

**Comment by ZarshaB** [comment]
13>> When I sort the cars, the arrow in option is overlapping the text. Please refer to attached picture. 
![image](https://user-images.githubusercontent.com/35685146/38189402-755a276a-3679-11e8-9db4-1ec9b8cf6824.png)

**Comment by ZarshaB** [comment]
14>>When I tried to delet my account, the buttons in message box were overlaping. Please refer to attached image.
![image](https://user-images.githubusercontent.com/35685146/38189422-8cfb290a-3679-11e8-8178-abec45e3a549.png)

**Comment by ZarshaB** [comment]
15>>
My Account Page
In certain cases, the car images were not displayed. For example, in my account section, My ads, purchase history, etc where the car details could be viewed along with the image, the image was blank

**Comment by ZarshaB** [comment]
16>> When I'm in my account section, the grey bar having all options should be realigned slightly towards the left. The last option (Purchase history) is almost touching the end of screen.
![image](https://user-images.githubusercontent.com/35685146/38189452-b559dcd4-3679-11e8-8207-9ccc2e7818d7.png)

**Comment by ZarshaB** [comment]
17>> Please see if the readability of grey bar having all options in My account section could be improved further.
![image](https://user-images.githubusercontent.com/35685146/38189480-ce15c1b6-3679-11e8-87de-8bf2bfdd1bf9.png)

**Comment by ZarshaB** [comment]
18>> Just for your info, when I tilt my fone and the page goes in horizonal view, things become overlapping escpecially the top headings of that particular page and in some cases, the diappear totally. See if you can fix them to maximum extent on your own.

**Comment by ZarshaB** [comment]
19>> Contact Us
In mobile number field, when all the required digits have been entered, it starts accepting the alphabets.

**Comment by asifjans** [comment]
2>> The font is not the same as website in banner. The headings have way too much of spacing. Additionally it is over lapping the search button. Please refer to picture attached. **(Fixed)**

8>> Register Page
Phone Number is taking all alphabets **(Fixed)**

10>> Login with facebook button is very blur. **(Fixed)**

14>>When I tried to delete my account, the buttons in message box were overlaping. Please refer to attached image. (This issue is appearing in 3,4,4s,5,5s iPhone) **(Fixed)**

16>> When I'm in my account section, the grey bar having all options should be realigned slightly towards the left. The last option (Purchase history) is almost touching the end of screen. **(Fixed)**

17>> Please see if the readability of grey bar having all options in My account section could be improved further. **(Fixed)**

**Comment by ZarshaB** [comment]
**Not Fixed**
2>> Slider is overlapping in iPhone 3,4,4s,5,5s
![image](https://user-images.githubusercontent.com/35685146/38201792-e2ee1cc6-36b2-11e8-9b10-de4f04f454f1.png)

**Comment by Anum444** [comment]
**These issues are Fixed and ready for testing..**

2>> The font is not the same as website in banner. The headings have way too much of spacing. Additionally it is over lapping the search button. Please refer to picture attached. (Fixed)
4>> Please decrease the size of testimonial pictures by 50%. The have taken way too much space on the screen. (Fixed)
5>> Please counter check the font on all pages. They appear different on different portions. For example, text in featured ads (Tickets Sold, Ad Description etc), banner and footer (download our app, follow us etc).
(Fixed)
6>> Please decrease the size of footer by 30-40% and increase the size of "Download our app" by 30%. (Fixed)
7>> When I clicked Learn More on How it Works on Homepage, the video did not play. I had to play it myself. Additionally, the sound is by default on mute. Please make it unmute. (Fixed)
11>> Plce your Ad page (Fixed)
Can all four headings (General Specification, Images and Mulkiya/Ownership Document) be aligned in one line? See if alignment in one line is not effecting the layout and looks nice. If it creates a hotchpotch, then let it be the way it is.
18>> Just for your info, when I tilt my fone and the page goes in horizonal view, things become overlapping escpecially the top headings of that particular page and in some cases, the diappear totally. See if you can fix them to maximum extent on your own.

**Comment by ZarshaB** [comment]
**Re-opened**
4>> Size is decreased but images are appearing compressed.

**Comment by asifjans** [comment]
2>> The font is not the same as website in banner. The headings have way too much of spacing. Additionally it is over lapping the search button. Please refer to picture attached. **(Not Fixed)**
![image](https://user-images.githubusercontent.com/35685146/38192989-1a5df6a6-3689-11e8-9394-29502a8a3d77.png)

**Comment by ZarshaB** [comment]
When I clicked on Login with facebook, it opened facebook page and prompted for facebook login. Shouldn't it pick the info from facebook app where I'm already logged-in

**Comment by ZarshaB** [comment]
**Re-opened**
18>>Fixed for site's menu but It is not fixed for My Account menu.

**Comment by ZarshaB** [comment]
20>> FAQs page is overlapping in iPhone in landscape mode. @Anum444

**Comment by ZarshaB** [comment]
18>> Just for your info, when I tilt my fone and the page goes in horizonal view, things become overlapping escpecially the top headings of that particular page and in some cases, the diappear totally. See if you can fix them to maximum extent on your own.

Menu is not scrolling down.
![image](https://user-images.githubusercontent.com/35685146/38190569-4a619304-367e-11e8-8d10-a0f2b46fcd73.png)

**Comment by ZarshaB** [comment]
21>> Buttons overlapping.
![image](https://user-images.githubusercontent.com/35685146/38304026-57c1ffda-3821-11e8-95df-70799c7cbd7b.png)
![image](https://user-images.githubusercontent.com/35685146/38304053-6bc30c72-3821-11e8-91e8-6bd487ad8918.png)

**Comment by asifjans** [comment]
19>> When I clicked on Login with facebook, it opened facebook page and prompted for facebook login. Shouldn't it pick the info from facebook app where I'm already logged-in
**(Fixed)**
