### ISSUE TITLE
Client's App Issues 8th May 2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#238]

**Comment by ZarshaB** [comment]
1>> Purchase History
When I click "I" in status, the window closes after pressing 5-6 times.

**Comment by ZarshaB** [comment]
2>> My Profile
 In gender, the radio buttons are not aligned. When specific gender is selected, you can see the white portion of radio button. Not filling it properly.

**Comment by ZarshaB** [comment]
3>> Ad deletion/ Place Ad
the radio buttons are not aligned. When specific gender is selected, you can see the white portion of radio button. Not filling it properly. Same issue while posting ad, deleting ad reasons and everywhere else.

**Comment by ZarshaB** [comment]
4>> View Cars
What is Download Our App and Social Media Footers doing in Specific Car View Page? Im already using the app.

**Comment by ZarshaB** [comment]
5>> Register/ View Cars
Please refer to attach picture. There is no point in having two Headers with Weladela. Same issue in both View Car and Register. Appears when Im using the app without login.

**Comment by ZarshaB** [comment]
6>> My Account
Headings are not centre aligned.

**(Sir asked to move all headings to left.)**

**Comment by ZarshaB** [comment]
7>> Cancel (Cross)
Cancel (cross on top of dialogue boxes) not working. For example, while redeeming rewards points, all the error messages that popped up had a cross button on top. But none of it is working.

**Comment by ZarshaB** [comment]
8>> My Cart
I added one car in My cart from hotmail account. For testing I logged in with outlook and gmail accounts and that car which added in my hotmail account is appearing in my outlook and gmail accounts

**Comment by Anum444** [comment]
**RFR**

2>> My Profile
In gender, the radio buttons are not aligned. When specific gender is selected, you can see the white portion of radio button. Not filling it properly.
3>> Ad deletion/ Place Ad
the radio buttons are not aligned. When specific gender is selected, you can see the white portion of radio button. Not filling it properly. Same issue while posting ad, deleting ad reasons and everywhere else.

**Comment by Anum444** [comment]
**RFR**

1>> Purchase History
When I click "I" in status, the window closes after pressing 5-6 times.

7>> Cancel (Cross)
Cancel (cross on top of dialogue boxes) not working. For example, while redeeming rewards points, all the error messages that popped up had a cross button on top. But none of it is working.

**Comment by Anum444** [comment]
**Fixed**

6>> My Account
Headings are not centre aligned.

(Sir asked to move all headings to left.)

**Comment by ZarshaB** [comment]
**Not Fixed**
8>> My Cart
I added one car in My cart from hotmail account. For testing I logged in with outlook and gmail accounts and that car which added in my hotmail account is appearing in my outlook and gmail accounts
