### ISSUE TITLE
UI - View Cars

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#33]

**Comment by ZarshaB** [comment]
1) Filters are not working.
![image](https://user-images.githubusercontent.com/35685146/35270172-19eca88a-0050-11e8-82c8-a15b1badff03.png)

**Comment by ZarshaB** [comment]
2) Layout issue.
![image](https://user-images.githubusercontent.com/35685146/35270194-2f3352fc-0050-11e8-9c29-7d6f32328d19.png)
![image](https://user-images.githubusercontent.com/35685146/35270215-4464d7f4-0050-11e8-87a6-0ad4bf7dc692.png)

**Comment by ZarshaB** [comment]
3) Font size and color is different than template.
![image](https://user-images.githubusercontent.com/35685146/35270306-94de744c-0050-11e8-913e-27d47ac1598e.png)

![image](https://user-images.githubusercontent.com/35685146/35270318-9e5cc668-0050-11e8-8be2-d32e7a6ff818.png)

**Comment by ZarshaB** [comment]
4) There should be first watch icon and then favourites icon as it is in template.
![image](https://user-images.githubusercontent.com/35685146/35270532-3f4ff6e4-0051-11e8-83f5-087ed66f9908.png)

![image](https://user-images.githubusercontent.com/35685146/35270523-363ea42e-0051-11e8-98c3-befdcfb51607.png)

**Comment by ZarshaB** [comment]
5) On clicking on "Search" it changes from grid to list view.
![image](https://user-images.githubusercontent.com/35685146/35270594-78282aea-0051-11e8-86cf-666000df2c91.png)

**Comment by ZarshaB** [comment]
6) Links color should be orange to specify that it is a link.
![image](https://user-images.githubusercontent.com/35685146/35270663-b12aed6e-0051-11e8-8bbe-088a217c0a63.png)

**Comment by ZarshaB** [comment]
7) Icons name should be "Add to Favourites" and "Watch",
![image](https://user-images.githubusercontent.com/35685146/35270757-dedbeb46-0051-11e8-942f-e8897885fe3f.png)

**Comment by ZarshaB** [comment]
8) Loading Icon that appears on clicking on "Watch" icon should be WelaDela exchange icon instead of this.
![image](https://user-images.githubusercontent.com/35685146/35270825-0f96a870-0052-11e8-893f-579e3b3942f7.png)

**Comment by ZarshaB** [comment]
9) Only main image of uploaded ad is appearing and other images does not appear.
![image](https://user-images.githubusercontent.com/35685146/35270933-5dc1109e-0052-11e8-85ee-254eb44052f1.png)

**Comment by ZarshaB** [comment]
10) Favourites icon color should be same in pop up as it is on page. That is grey in color but changes color to orange on hover.
![image](https://user-images.githubusercontent.com/35685146/35271067-c49c64d0-0052-11e8-84ec-5be7ffbfbfb3.png)
![image](https://user-images.githubusercontent.com/35685146/35271080-cc6f1ed2-0052-11e8-88f2-6af9eca68d56.png)

**Comment by ZarshaB** [comment]
11) Layout changes for uploaded ad.
![image](https://user-images.githubusercontent.com/35685146/35271187-17f53ee0-0053-11e8-9c6f-06a8c7424edd.png)

**Comment by ZarshaB** [comment]
12) Filters are not complete and also names should be bold, same font and not all capitalized as shown in template.
![image](https://user-images.githubusercontent.com/35685146/35274163-ef5900de-005c-11e8-933f-f642901b46dc.png)
![image](https://user-images.githubusercontent.com/35685146/35274230-24362d68-005d-11e8-8b90-bcf4a108dadf.png)

**Comment by ZarshaB** [comment]
13) Images are not displaying.
![image](https://user-images.githubusercontent.com/35685146/35284468-b91493a6-007c-11e8-9b01-d508bd07d588.png)

**Comment by ZarshaB** [comment]
1,2,3,6,7,8,10,12 >> are not Fixed.
9,11 >> We could test these after ad will go live.

**Comment by ZarshaB** [comment]
14) Color should be orange.

**Comment by ZarshaB** [comment]
15) Heading should not be all capitalised. 
![image](https://user-images.githubusercontent.com/35685146/35331165-25919bb8-0128-11e8-83cc-0a31de3bcce4.png)

**Comment by ZarshaB** [comment]
16) Pop up format should be same as it is on Car detail page.
![image](https://user-images.githubusercontent.com/35685146/35331246-74440e4e-0128-11e8-9930-9fb9c669f2c4.png)

**Comment by ZarshaB** [comment]
17) Cross icon of pop up should be orange,
![image](https://user-images.githubusercontent.com/35685146/35331508-7b25e146-0129-11e8-88ad-5803d4b34d3f.png)
![image](https://user-images.githubusercontent.com/35685146/35331516-83ee0b00-0129-11e8-9358-8bfab21dfe90.png)

**Comment by ZarshaB** [comment]
18) On clicking on "Favourites" icon without login , user should be redirected to Login page.

**Comment by ZarshaB** [comment]
19) Please remove login from this error message, as it is already at login page.
This should be for clicking on "Favourites" from Our Featured Cars section, view Cars page and Car detail page.
![image](https://user-images.githubusercontent.com/35685146/35338994-2b9a449c-0141-11e8-9109-949e19afdba4.png)

**Comment by ZarshaB** [comment]
20) Timer is not correct.
![image](https://user-images.githubusercontent.com/35685146/35339040-5abf8728-0141-11e8-85f4-e42ece448e44.png)

**Comment by ZarshaB** [comment]
21) Please make it on highest and lowest values by default.
![image](https://user-images.githubusercontent.com/35685146/35379355-a5727ac8-01d7-11e8-805d-65a956505b3d.png)

**Comment by ZarshaB** [comment]
22) By default it should be "1" .
And please make it plus sign upward and minus sign downwards.
![image](https://user-images.githubusercontent.com/35685146/35379708-c9272bac-01d8-11e8-95d2-5e75770a4adc.png)

**Comment by ZarshaB** [comment]
23) Please change "Buy Now" to "Buy Car".
![image](https://user-images.githubusercontent.com/35685146/35430330-9b3f8bc8-0299-11e8-9e8f-1cc98328f7cf.png)

**Comment by ZarshaB** [comment]
24) Please make price in decimal not in integer.
![image](https://user-images.githubusercontent.com/35685146/35430364-c6afd7ae-0299-11e8-85c6-ebaf541c638d.png)
![image](https://user-images.githubusercontent.com/35685146/35430391-d571f1b4-0299-11e8-9c55-12c2ce808628.png)

**Comment by ZarshaB** [comment]
23) Please remove separator line below AED and and reduce space between Ticket sold and AED to match space of heading and Ticket sold.
![image](https://user-images.githubusercontent.com/35685146/35444662-0ce16b7a-02d1-11e8-8ae2-6e96d9e3d224.png)

**Comment by ZahidRavian** [comment]
These issues are fixed
17,21,22

**Comment by ZahidRavian** [comment]
These issues are also fixed
2,4,7,10,23

**Comment by ZarshaB** [comment]
2) Not Fixed.
Space and layout is okay now. But text is not bold.
![image](https://user-images.githubusercontent.com/35685146/35499410-01a6a3d6-04f4-11e8-8c41-3c2d88a7d428.png)

**Comment by ZarshaB** [comment]
7) Not Fixed.
It is fixed for View cars page, but on pop up for "Watch" it is still Add to wishlist. Please also change there.
![image](https://user-images.githubusercontent.com/35685146/35499479-432a350c-04f4-11e8-9e3d-7a7b17d7ea2e.png)

**Comment by ZarshaB** [comment]
10) Not fixed.
Color does not change to orange on Hover.
![image](https://user-images.githubusercontent.com/35685146/35499501-643f63a2-04f4-11e8-8c90-55cf0baea579.png)

**Comment by ZarshaB** [comment]
11) Please make this message as " Please Login/Register to add to your Favourites".
![image](https://user-images.githubusercontent.com/35685146/35500444-4f5c9f82-04f8-11e8-8025-ca57a23e45a3.png)

**Comment by asifjans** [comment]
1) Fixed.

**Comment by ZarshaB** [comment]
7) It should be "Watch" instead of "Quick View".
![image](https://user-images.githubusercontent.com/35685146/35557347-b170ae6a-05c6-11e8-8b29-d58c93e4a725.png)

**Comment by ZarshaB** [comment]
21) Please make it "Add to Favourites" instead of "Add to Favourite".
![image](https://user-images.githubusercontent.com/35685146/35557425-ee73808a-05c6-11e8-956d-416c57556465.png)

**Comment by ZarshaB** [comment]
22) Circle should not appear with heart icon. It should be same as it is for other ads.
![image](https://user-images.githubusercontent.com/35685146/35557538-3721339a-05c7-11e8-828a-26de073c0d50.png)
![image](https://user-images.githubusercontent.com/35685146/35557554-434d24ee-05c7-11e8-800f-e2a84d7243fc.png)

**Comment by ZarshaB** [comment]
1) When I search with minimum AED 207 as ticket price, then it also shows me cars with  AED 0.
![image](https://user-images.githubusercontent.com/35685146/35557877-4b521676-05c8-11e8-8133-3c20a4254c81.png)

**Comment by ZarshaB** [comment]
23) Values of search criteria should reset when user again clicks on "View Cars" page.

**Comment by ZarshaB** [comment]
24) If year range is selected in minimum as 2003 then in maximum range it should show years greater than 2003 or at least it does not allow to select year less than 2003.
![image](https://user-images.githubusercontent.com/35685146/35558702-91721da2-05ca-11e8-946b-ee8a5b24cffa.png)

**Comment by ZarshaB** [comment]
25) When I select all search criteria then on clicking on "Search" it does not save value for "Car model".
![image](https://user-images.githubusercontent.com/35685146/35558773-b19451ea-05ca-11e8-81d1-aa1c8bd6eff3.png)

**Comment by ZarshaB** [comment]
26) Please correct spelling mistake and change it to  "mileage"
![image](https://user-images.githubusercontent.com/35685146/35558821-d63cb7c6-05ca-11e8-8aae-96fa791dda22.png)

**Comment by ZarshaB** [comment]
27) Please make it bold and in center.
![image](https://user-images.githubusercontent.com/35685146/35558863-f29ac5fc-05ca-11e8-8d02-b61e814dbeee.png)

**Comment by ZarshaB** [comment]
28) Please remove this line below AED and also reduce space.
![image](https://user-images.githubusercontent.com/35685146/35558978-3d450d4c-05cb-11e8-8621-19d0821f2d54.png)

**Comment by ZarshaB** [comment]
29) Image becomes stretched when I change the layout view from Grid to List.
![image](https://user-images.githubusercontent.com/35685146/35559241-0b05b20e-05cc-11e8-88b5-5f85c17a9939.png)

![image](https://user-images.githubusercontent.com/35685146/35559282-2d68c2c8-05cc-11e8-997e-4decd81cf8aa.png)

**Comment by ZarshaB** [comment]
30) Maximum value should not go to maximum place. It should remain there at place where it was before clicking on "Search" button.
![image](https://user-images.githubusercontent.com/35685146/35559936-c5cb66dc-05cd-11e8-88b9-ba2f88a50470.png)
![image](https://user-images.githubusercontent.com/35685146/35559943-cdb02888-05cd-11e8-9fec-4b32f764e6c4.png)

**Comment by ZarshaB** [comment]
31) On clicking on "Add to Favourites" , pop up should be displayed on current page instead of redirecting it to Home page.

**Comment by ZarshaB** [comment]
32) Time left is not appearing in pop up.
![image](https://user-images.githubusercontent.com/35685146/35561995-d05fcbaa-05d3-11e8-9f62-0906bb7a10ce.png)

**Comment by ZarshaB** [comment]
33) Tickets Sold should show sold tickets.
![image](https://user-images.githubusercontent.com/35685146/35564723-e8b30fec-05dc-11e8-819c-8bbdb994f206.png)

**Comment by asifjans** [comment]
@ZarshaB  Please remove the issues those are fixed.

**Comment by ZarshaB** [comment]
34) If I upload ad having long title then layout changes.
![image](https://user-images.githubusercontent.com/35685146/35617462-18eadf2e-069a-11e8-90f7-aa9fbe4adcd6.png)

And also image does not appear if I change view and Title is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35617505-331255bc-069a-11e8-9943-af922ec40d18.png)

**Comment by ZarshaB** [comment]
Not Fixed:
20, 7, 21,22, 1, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33'

New Logged = 34

**Comment by ZarshaB** [comment]
Functional Issues = 1,20, 23, 24, 25, 30, 31, 32, 33

**Comment by ZarshaB** [comment]
35) When a specific car ad is opened, the image is not getting enlarged when I click on the picture.

**Comment by ZarshaB** [comment]
36) There should be a Reset button for resetting filters

**Comment by ZarshaB** [comment]
37)  Please make the max value of price filter up to 1500.

**Comment by ZarshaB** [comment]
38) When price filter is applied for certain value and results are displayed, the bar gets reset to extreme ends whereas value remains within the specified range. Please make necessary rectifications.

**Comment by ZarshaB** [comment]
39) In warranty and service history, when we select any value, it will display that value alone and the customer will not have any clue what that value is for. For example, in Service history, when I choose Yes, the option will be displayed as Yes only while not mentioning what this Yes is for. It is very confusing. Same can be observed in other fields as well. So I'd recommend that  we switch to radio buttons or check boxes for Transmission Type, Fuel Type, Warranty, regional Specs and Service History.

**Comment by ZarshaB** [comment]
40) When quick view button is clicked and ad is displayed, the cross button at the top is touching the Ad title. Additionally, the button is not a perfect circle.

**Comment by ZarshaB** [comment]
41) Sort by is not showing correct results, as if I select low to high then it shows AED 0 at wrong place. Same is case for selecting criteria of high to low.

![image](https://user-images.githubusercontent.com/35685146/35674375-52fbce04-0766-11e8-811b-56dde9ea21b6.png)

**Comment by ZarshaB** [comment]
42) Please make it first "Favourite" and then "watch" icon as it is on Home page.
![image](https://user-images.githubusercontent.com/35685146/35677162-62c8909c-0770-11e8-8f38-3972b5db000d.png)

**Comment by ZarshaB** [comment]
43) Last image is not completely visible in pop up.
![image](https://user-images.githubusercontent.com/35685146/35725388-0dab30b6-0823-11e8-8270-41cca4397638.png)
