### ISSUE TITLE
UI - Register

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#37]

**Comment by ZarshaB** [comment]
This line is not mentioned in requirement document.
![image](https://user-images.githubusercontent.com/35685146/35222427-a89cd8a4-ff9f-11e7-896f-d2bad191f0c4.png)

**Comment by ZarshaB** [comment]
It should be ad's status.
![image](https://user-images.githubusercontent.com/35685146/35222677-8c7753e2-ffa0-11e7-8c12-25cc443dafd8.png)

**Comment by ZarshaB** [comment]
"Login Page" link should be hyperlinked. And it should redirect to Login Page as redirecting to error page.
![image](https://user-images.githubusercontent.com/35685146/35264380-610c8cf6-003e-11e8-9d67-919b7e18399c.png)

**Comment by ZarshaB** [comment]
Middle name, Gender, Hear About Us are not required fields.
All other fields should be mentioned  required with asterisk and should be similar to all required fields.
![image](https://user-images.githubusercontent.com/35685146/35264463-a756929c-003e-11e8-8957-c3df4a5e767f.png)

**Comment by ZarshaB** [comment]
Error message should be in red color not in orange.
![image](https://user-images.githubusercontent.com/35685146/35264514-db9c154a-003e-11e8-98b7-ea9d3878fbe7.png)

**Comment by ZarshaB** [comment]
Telephone field is not required.
![image](https://user-images.githubusercontent.com/35685146/35264570-14acc50a-003f-11e8-96fd-e2507cf87e51.png)

**Comment by ZarshaB** [comment]
This error message is not correct 
![image](https://user-images.githubusercontent.com/35685146/35264588-26324624-003f-11e8-8943-9856578483c2.png)

**Comment by ZarshaB** [comment]
There should be "Register" button instead of "Continue".
![image](https://user-images.githubusercontent.com/35685146/35267804-46ebbdaa-0049-11e8-9c55-3f93f48fc7e2.png)

**Comment by ZarshaB** [comment]
It should be ad's status.
![image](https://user-images.githubusercontent.com/35685146/35267825-5c687c36-0049-11e8-99f1-3126773edf20.png)

**Comment by ZarshaB** [comment]
Hover should be orange.
![image](https://user-images.githubusercontent.com/35685146/35267878-79e40f96-0049-11e8-875c-d18da9d04a7e.png)

**Comment by ZarshaB** [comment]
This field should be a drop down.
![image](https://user-images.githubusercontent.com/35685146/35267917-910c2dc0-0049-11e8-9cc6-199867e3bd31.png)

**Comment by ZarshaB** [comment]
There should be a check in DOB as it is allowing to enter DOB for future and current years.
![image](https://user-images.githubusercontent.com/35685146/35267937-a644eaf6-0049-11e8-9c55-0b444cddced1.png)

**Comment by ZarshaB** [comment]
It should not accept alphabats in mobile number field.
![image](https://user-images.githubusercontent.com/35685146/35267971-ba6e07a6-0049-11e8-8981-e81227c04d04.png)

**Comment by ZarshaB** [comment]
No captcha.

**Comment by ZarshaB** [comment]
This line is not mentioned in requirement document.
![image](https://user-images.githubusercontent.com/35685146/35268071-f80db49e-0049-11e8-9a65-c51368c8cd93.png)

**Comment by ZarshaB** [comment]
Country code is appearing as an extra part on Firefox but look reasonable on Chrome. Also field name is not at centre of field like other fields.
![image](https://user-images.githubusercontent.com/35685146/35268104-0ccb957c-004a-11e8-926d-4c9c980b8935.png)

**Comment by ZarshaB** [comment]
This text on button should not be all capitalised but it should only have first word capital.
![image](https://user-images.githubusercontent.com/35685146/35268164-31be419a-004a-11e8-988f-05381f734c1a.png)

**Comment by ZarshaB** [comment]
All buttons should have only First letter of a word capital not whole word capitalized.
![image](https://user-images.githubusercontent.com/35685146/35268252-6c8b0df8-004a-11e8-822e-437da3e6a05c.png)

**Comment by ZarshaB** [comment]
"Please" spelling mistake in Register email template.
![image](https://user-images.githubusercontent.com/35685146/35268284-7f53d2b2-004a-11e8-8296-51cfb3a6e202.png)

**Comment by ZarshaB** [comment]
WelaDela logo should be at left aligned with inner box in email template.

![image](https://user-images.githubusercontent.com/35685146/35268315-91e9ceae-004a-11e8-8670-2acdd70a236d.png)

**Comment by ZarshaB** [comment]
Text font of email template is not correct.
![image](https://user-images.githubusercontent.com/35685146/35268346-a6588f4c-004a-11e8-9f52-7f430f39ace3.png)

**Comment by ZarshaB** [comment]
Both links should be of blue color in email template.
![image](https://user-images.githubusercontent.com/35685146/35268371-bc2e7a52-004a-11e8-8632-4bd43de20f1a.png)

**Comment by ZarshaB** [comment]
When I take cursor on email then email disappears in email template.
![image](https://user-images.githubusercontent.com/35685146/35268434-f6af87d4-004a-11e8-8178-08655d80a5a5.png)

**Comment by ZarshaB** [comment]
"Cheers" size in email templates is greater in size than provided in template.
![image](https://user-images.githubusercontent.com/35685146/35268463-07c14e18-004b-11e8-8867-6fcf9b2a9545.png)
![image](https://user-images.githubusercontent.com/35685146/35268519-2a58b97a-004b-11e8-822c-bb3020b9f3f3.png)

**Comment by ZarshaB** [comment]
Welcome Email is missing car ads picture and link.
![image](https://user-images.githubusercontent.com/35685146/35268556-402d676e-004b-11e8-85eb-b3c7d278241c.png)
![image](https://user-images.githubusercontent.com/35685146/35268567-46ca23a0-004b-11e8-902f-bfcfb5435813.png)

**Comment by ZarshaB** [comment]
In email it should be "WelaDela" instead of "Weladela".
![image](https://user-images.githubusercontent.com/35685146/35268591-599a342a-004b-11e8-835d-125a0532c205.png)

**Comment by ZarshaB** [comment]
Customer name should have bigger font than the rest of text as it is in template.
![image](https://user-images.githubusercontent.com/35685146/35268612-6af2af18-004b-11e8-9422-91293afe8fca.png)
![image](https://user-images.githubusercontent.com/35685146/35268627-76fbf85a-004b-11e8-89af-8c07529a7c35.png)

**Comment by ZarshaB** [comment]
Subject of welcome email should be "Welcome to weladela.com".
![image](https://user-images.githubusercontent.com/35685146/35268673-91943772-004b-11e8-8d1c-ddfc3d2108b7.png)

**Comment by ZarshaB** [comment]
It is giving me download link for logo in email template.

**Comment by ZarshaB** [comment]
30) City (drop down) and Passport number fields are missing. Both are required fields.
![image](https://user-images.githubusercontent.com/35685146/35268976-860e2bb4-004c-11e8-9c12-ed55d6d2dc29.png)

**Comment by ZarshaB** [comment]
31) Fields name should be Email Id, Emirates Id, Where did you hear about us? , Confirm Password.

**Comment by ZarshaB** [comment]
32) After clicking on "Verify Account" link, there is so much space on redirected page.
![image](https://user-images.githubusercontent.com/35685146/35269056-b3e4e3b6-004c-11e8-8ec4-41182fea6f2a.png)

**Comment by ZarshaB** [comment]
33) "Terms and conditions" and "Login" should have orange color to specify that it is a link. As it is for "Forgot your password?"
![image](https://user-images.githubusercontent.com/35685146/35269077-ce703334-004c-11e8-925f-695ac0ddce90.png)

**Comment by ZahidRavian** [comment]
2-Fixed
3-Fixed
4-Fixed
5-Fixed
6-Fixed
7-Fixed
8-Fixed
9-Fixed
10-Fixed
11-Fixed
13-Fixed
19-Fixed
26-Fixed
28-Fixed
31-Fixed
32-Fixed
33-Fixed

**Comment by ZarshaB** [comment]
7) Error message should not be there when I come to Register page. It should only appear when I submit form without checking terms and conditions.
![image](https://user-images.githubusercontent.com/35685146/35283147-37c8304e-0079-11e8-97f9-82ce51bbeb0a.png)

**Comment by ZarshaB** [comment]
10) Gender's radio button should also be orange.
![image](https://user-images.githubusercontent.com/35685146/35283182-53008348-0079-11e8-9995-b337283efc8b.png)

**Comment by ZarshaB** [comment]
13) If I enter alphabets in mobile number field then error should mention "Please enter valid mobile number". It keeps on giving this field is required and will confuse user.
![image](https://user-images.githubusercontent.com/35685146/35283243-8b32c884-0079-11e8-940f-c1f752a04f71.png)

**Comment by ZarshaB** [comment]
32) Still appearing the same.

**Comment by ZarshaB** [comment]
34) This link is not clickable.
![image](https://user-images.githubusercontent.com/35685146/35285853-369ce24e-0080-11e8-9cc6-7319723d377f.png)

**Comment by ZahidRavian** [comment]
7-Fixed
10-Fixed
13-Need discussion
32-Need discussion
34-Fixed

**Comment by ZarshaB** [comment]
7) Fixed.
10) Fixed on Chrome but not on Firefox. ( Low Priority)
13) Fixed on Chrome but not on Firefox.  ( Low Priority)
32) Fixed.
34) Fixed.
22) Fixed.

**Comment by ZarshaB** [comment]
Not Fixed.
1,12,14,15,16,17,18,20,21,24,25,27,29,33

**Comment by ZarshaB** [comment]
Not Fixed:
14, 18 ( Please make button text bold otherwise it is correct.) , 20, 21, 22 ( Link color is dark blue please make it to default blue color.) , 23, 24, 25, 27, 29

**Comment by ZahidRavian** [comment]
These issues are fixed 
1,12,14,15,17,18 ,21,,29,33

**Comment by ZarshaB** [comment]
Not Fixed:
14, 18 ( Please make button text bold otherwise it is correct.) , 20, 21, 22 ( Link color is dark blue please make it to default blue color.) , 23, 24, 25, 27, 29

**Comment by ZarshaB** [comment]
34) I have to select two times from DOB then errors disappears.
![image](https://user-images.githubusercontent.com/35685146/35396154-f6875484-020d-11e8-8acc-98b2a105f9ae.png)

**Comment by ZarshaB** [comment]
35) Make 4 boxes for Emirates Id.
![image](https://user-images.githubusercontent.com/35685146/35430193-044bbeee-0299-11e8-9885-919615bc92fe.png)

**Comment by ZarshaB** [comment]
36) Make it required field.
![image](https://user-images.githubusercontent.com/35685146/35430206-1756ec34-0299-11e8-9b88-cacbfbd83bf4.png)

**Comment by ZarshaB** [comment]
37) It should only allow 9 digits.
![image](https://user-images.githubusercontent.com/35685146/35430222-29e5b9b6-0299-11e8-8c8b-5248db29fc02.png)

**Comment by ZarshaB** [comment]
38) It should only take numbers.
![image](https://user-images.githubusercontent.com/35685146/35430248-4087e446-0299-11e8-9e8b-320f3e9e3f20.png)

**Comment by ZarshaB** [comment]
39) This error message should appear at mentioned place.
![image](https://user-images.githubusercontent.com/35685146/35430279-66ca7632-0299-11e8-9d8d-7e95de5a638a.png)

**Comment by ZahidRavian** [comment]
These issues are fixed
35, 36, 37, 38, 39

**Comment by ZarshaB** [comment]
40) Please mention field's name instead of "This"
![image](https://user-images.githubusercontent.com/35685146/35511871-7986b2a8-051f-11e8-99ab-191087f8d9fb.png)

**Comment by ZarshaB** [comment]
41) Please make it hyperlinked to site.
![image](https://user-images.githubusercontent.com/35685146/35512360-563a29b8-0521-11e8-87b8-ec1515d9ea1d.png)

**Comment by ZarshaB** [comment]
42) Passport field required error message.
![image](https://user-images.githubusercontent.com/35685146/35517094-4842bcf4-052f-11e8-9d17-16d373fa3b3d.png)

**Comment by ZarshaB** [comment]
43) Please correct this error message. It will only accept 10 digits. No less than this.
![image](https://user-images.githubusercontent.com/35685146/35517159-72c46bd0-052f-11e8-83ce-53bc2957b67d.png)

**Comment by asifjans** [comment]
@ZarshaB  Can you please re-test and remove the issues those are fixed.

**Comment by ZarshaB** [comment]
44) Please mention "field" as it is mentioned for all other fields.
"Hear About Us field is required".
![image](https://user-images.githubusercontent.com/35685146/35555309-912e46cc-05c0-11e8-982c-115fbe7e29f9.png)

**Comment by ZarshaB** [comment]
45) It is keep on giving me error message for any number of digits.
![image](https://user-images.githubusercontent.com/35685146/35555417-eca04622-05c0-11e8-946d-bc6ef3cdec66.png)

**Comment by ZarshaB** [comment]
14,34,44, 45 >> Not Fixed

**Comment by ZarshaB** [comment]
46) Please make these lines bold.
![image](https://user-images.githubusercontent.com/35685146/35615044-d6596dbc-0692-11e8-81fb-2c3910d080ed.png)

**Comment by ZarshaB** [comment]
47) It should not accept Emirates Id less than the mention places. As now it is accepting if I only enter one digit. It should display error:
"Please enter valid Emirates Id."
![image](https://user-images.githubusercontent.com/35685146/35615487-1692e416-0694-11e8-81d6-fc9989adfddb.png)

**Comment by ZarshaB** [comment]
48) Please remove mobile number from error message. 
![image](https://user-images.githubusercontent.com/35685146/35670556-b3225e58-075a-11e8-90c9-06e0a4c84d3f.png)

**Comment by ZarshaB** [comment]
Not Fixed= 14,34,42,44.45.46,47,48
Functional = 48,47,45,42,34

**Comment by ZarshaB** [comment]
44) Please make U capital in "Hear About Us field is required".
