### ISSUE TITLE
Responsive Issues Android

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#61]

**Comment by ZarshaB** [comment]
1) Header should be small. Buttons alignment is not correct.
Menu's outline should not be double from below. 
![image](https://user-images.githubusercontent.com/35685146/35569269-983b3baa-05ed-11e8-90c0-bfb3b1ad5a6c.png)

**Comment by ZarshaB** [comment]
2) Buttons should be reduce in width. And "Learn More" button's text should be small then other button's text.
![image](https://user-images.githubusercontent.com/35685146/35569336-c460e810-05ed-11e8-808a-17ba0f8ece0a.png)

**Comment by ZarshaB** [comment]
3) Footer's Alignment is not correct and also reduce space.
![image](https://user-images.githubusercontent.com/35685146/35569475-ef943640-05ed-11e8-9633-b8a5765c3313.png)

**Comment by ZarshaB** [comment]
5) Font of menu should be same as site's. All words should not be capital.
![image](https://user-images.githubusercontent.com/35685146/35569538-2b2e6770-05ee-11e8-9136-d6f39cdc8dc9.png)

**Comment by ZarshaB** [comment]
6) Selected menu should not turn to red.
![image](https://user-images.githubusercontent.com/35685146/35569573-3bf379ba-05ee-11e8-9589-4a4f6997db11.png)

**Comment by ZarshaB** [comment]
7) Extra space on pages.
![image](https://user-images.githubusercontent.com/35685146/35569596-4c7a9c0a-05ee-11e8-80de-e01a9e1f37a1.png)

**Comment by ZarshaB** [comment]
8) Alignment Issue:
![image](https://user-images.githubusercontent.com/35685146/35569615-6514c984-05ee-11e8-93f5-6a5c707b6c4b.png)

**Comment by ZarshaB** [comment]
9) Images are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35569734-c1df7d6c-05ee-11e8-8c0e-b0e65e887681.png)

**Comment by ZarshaB** [comment]
10) Layout if Timer is not appearing correct anywhere.
![image](https://user-images.githubusercontent.com/35685146/35569828-174ec550-05ef-11e8-8fd4-ee74f66784ef.png)

**Comment by ZarshaB** [comment]
11) It is not scrollable. I have to click in order to select the price.
![image](https://user-images.githubusercontent.com/35685146/35569894-5870c4d4-05ef-11e8-911d-904925b60218.png)

**Comment by ZarshaB** [comment]
12) Whole image is not appearing in frame.
![image](https://user-images.githubusercontent.com/35685146/35569923-71ad89d2-05ef-11e8-8ba9-fed89873468c.png)

**Comment by ZarshaB** [comment]
13) On Home page "Our Featured Cars" heading is not visible. Slider is not visible.
I have to click on cars and then it's icons ( Watch , Add to Favourites, side arrows) appear.

**Comment by ZarshaB** [comment]
14) Buttons are not appearing correct in pop up.
![image](https://user-images.githubusercontent.com/35685146/35570095-f422adfc-05ef-11e8-90c1-7b627d565bde.png)

**Comment by ZarshaB** [comment]
15) Heading is not visible.
![image](https://user-images.githubusercontent.com/35685146/35570121-098e77e8-05f0-11e8-9e76-7e764ad2d14a.png)

**Comment by ZarshaB** [comment]
16) Complete Register page is not visible.
![image](https://user-images.githubusercontent.com/35685146/35570136-1a78c3ec-05f0-11e8-85de-ab1e550f4c4c.png)

**Comment by ZarshaB** [comment]
17) Complete page is not available.
Forgot your Password should appear on next line.
![image](https://user-images.githubusercontent.com/35685146/35570224-6937d9fa-05f0-11e8-97c0-74788a3e2519.png)

**Comment by ZarshaB** [comment]
18) All the pages where I have to type something like Upload Ad and Login/Register pages, on clicking on field it hides the field. Like this:
![image](https://user-images.githubusercontent.com/35685146/35570291-97d621c2-05f0-11e8-8411-78d9f07a4723.png)

**Comment by ZarshaB** [comment]
19) Alignment Issue of buttons and buttons are not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/35570320-b0db4288-05f0-11e8-9dfb-e380de1aad41.png)

**Comment by ZarshaB** [comment]
20) Terms and conditions of Order Summary page should appear on next line.
![image](https://user-images.githubusercontent.com/35685146/35570358-cabed2be-05f0-11e8-8c41-c8ff5c246d50.png)

**Comment by ZarshaB** [comment]
21) Complete page is not visible.
![image](https://user-images.githubusercontent.com/35685146/35570374-da1af954-05f0-11e8-9a13-76c8299eab65.png)

**Comment by ZarshaB** [comment]
22) Upper tabs are not visible as it is on Place your Ad page.
Broken images are available on Image pages by default.
![image](https://user-images.githubusercontent.com/35685146/35570423-fe54cc82-05f0-11e8-84b8-b91562ce64bf.png)

**Comment by ZarshaB** [comment]
23) As complete pages are not visible so error messages also do not show.

**Comment by ZarshaB** [comment]
24) It does not allow to choose from gallery.
![image](https://user-images.githubusercontent.com/35685146/35570489-2c17ab44-05f1-11e8-9d90-b1443dfae119.png)

**Comment by ZarshaB** [comment]
25) On landscape mode only header is visible.
![image](https://user-images.githubusercontent.com/35685146/35570529-446f0746-05f1-11e8-9030-d33473564933.png)

**Comment by ZarshaB** [comment]
26) Complete page is not visible.
![image](https://user-images.githubusercontent.com/35685146/35570559-5518750a-05f1-11e8-907a-d32d8f3da48c.png)

**Comment by ZarshaB** [comment]
27) How it works heading should be small.
![image](https://user-images.githubusercontent.com/35685146/35570579-65f1c0f2-05f1-11e8-92f4-39a13b3167c6.png)

**Comment by asifjans** [comment]
1, 3, 4, 5, 7, 9, 10, 14, 19 (Fixed)

**Comment by ZarshaB** [comment]
1,3,7,9 >> Fixed
5>> Font is okay but it should not be all capital but only first word capital as it is on site.
10 >> Not Fixed
14 >> Buttons are now appearing okay but are not exactly aligned. And also when I click on button then it's shape changes and it becomes small.
19 >> Search and Reset buttons are not appearing okay.

**Comment by ZarshaB** [comment]
27) In pop up of "Watch" complete cars images are not showing. And when I select any one car then images does not move forward.
![image](https://user-images.githubusercontent.com/35685146/35736073-98cd9b8c-0848-11e8-8dc5-a6ba1ba969c4.png)

**Comment by ZarshaB** [comment]
28) Search field is not appearing on slider.

**Comment by ZarshaB** [comment]
17)  Search and Reset buttons are not appearing okay.
![image](https://user-images.githubusercontent.com/35685146/35688255-93509b02-0792-11e8-8b8b-1b37be2f8a9a.png)

**Comment by ZarshaB** [comment]
18) Please remove the extra space and reduce space of header and Footer so that site is more visible.
![image](https://user-images.githubusercontent.com/35685146/35849092-3d175db2-0b42-11e8-812d-2d670cae6ad8.png)

**Comment by ZarshaB** [comment]
19) Side arrows of pop up are not working. And complete images are not appearing.
![image](https://user-images.githubusercontent.com/35685146/35849136-626a74aa-0b42-11e8-9cb2-04f62642f920.png)

**Comment by ZarshaB** [comment]
20) Alignment Issue:
![image](https://user-images.githubusercontent.com/35685146/35849161-774a30a4-0b42-11e8-90f4-a6dbc95bcc6f.png)

**Comment by ZarshaB** [comment]
21) Screen should not be scrollable.
![image](https://user-images.githubusercontent.com/35685146/35849617-0f1bac7c-0b44-11e8-855e-701636aa5d71.png)

**Comment by ZarshaB** [comment]
24) On clicking on buttons, it's shape changes but it does not redirects to any page.
![image](https://user-images.githubusercontent.com/35685146/35849777-942b5a20-0b44-11e8-8160-530e03749078.png)
![image](https://user-images.githubusercontent.com/35685146/35849790-9dc03bbe-0b44-11e8-8d1e-9a01802473e5.png)

**Comment by ZarshaB** [comment]
25) Overlapping issue.
![image](https://user-images.githubusercontent.com/35685146/35849820-b36af08a-0b44-11e8-8026-ce4c882635c3.png)

**Comment by ZarshaB** [comment]
26) Filled radio button is appearing like this:
![image](https://user-images.githubusercontent.com/35685146/35849842-cd09e7e4-0b44-11e8-848b-0b0024d61788.png)

**Comment by ZarshaB** [comment]
27) I have to select two times then error goes out.

![image](https://user-images.githubusercontent.com/35685146/35849964-1ed36f64-0b45-11e8-8617-9bde6c624082.png)

**Comment by ZarshaB** [comment]
28) On clicking on "Save" button of "Place your Ad" it redirects me to blank page.

![image](https://user-images.githubusercontent.com/35685146/35849993-3da999d6-0b45-11e8-9572-6bb16c1d7b36.png)

**Comment by asifjans** [comment]
26,25,24,22,21,20,18,17,15,9,8,7,6,4,2,1 (FIXED)

**Comment by ZarshaB** [comment]
Fixed = 7,8,9,20,21,22,23,24,25,28

**Comment by ZarshaB** [comment]
Not Fixed 
1>> Buttons shape is correct but Learn More button should be small then Buttons.
![image](https://user-images.githubusercontent.com/35685146/35981468-24018b12-0d0f-11e8-8ba7-fefb4eca0700.png)
2,4,6,15,17,26
3>> Fixed but alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/35981364-e388139e-0d0e-11e8-8a70-81645d24bb95.png)
18>> Header and Footer space is okay but there is space above slider.

**Comment by ZarshaB** [comment]
28) Please make it "Ad" instead of "Add" and button name should be "Login/Register".
![image](https://user-images.githubusercontent.com/35685146/35982010-85552d28-0d10-11e8-9095-402a5d309b5f.png)

**Comment by ZarshaB** [comment]
29) On login Login button should change to customer's name.

**Comment by ZarshaB** [comment]
Fixed >> 1,6,12

**Comment by ZarshaB** [comment]
30) Inovedia logo is not appearing correct at Footer.
![image](https://user-images.githubusercontent.com/35685146/36062652-4c4ce088-0e92-11e8-8954-a77dab62a410.png)

31) Please make it "Login/Register" instead of "Logn/Register" on button.

**Comment by asifjans** [comment]
28, 29 (Fixed)

**Comment by ZarshaB** [comment]
28) Please remove this line.
![image](https://user-images.githubusercontent.com/35685146/36158881-3949e75a-10ff-11e8-99a4-dfc28d7546ad.png)

29>> Text is overlapping and is not completely appearing.
![image](https://user-images.githubusercontent.com/35685146/36158909-4c795d6a-10ff-11e8-8b9d-0045ff277360.png)

30>> Button's color and placement is not correct and according to site. Images should be small to maintain consistency.
![image](https://user-images.githubusercontent.com/35685146/36159043-965082d8-10ff-11e8-8bfa-512b36d8ec71.png)

**Comment by ZarshaB** [comment]
32>> Menu should be bold.
![image](https://user-images.githubusercontent.com/35685146/36159424-7c26d334-1100-11e8-903e-bff45c6dfe0a.png)

**Comment by ZarshaB** [comment]
33>> Email template is appearing stretched on mobile. And also on clicking on link the page that appears has so much extra space on mobile.

**Comment by ZarshaB** [comment]
34>> On Terms and conditions page Footer alignment for Follow Us gets disturb.
![image](https://user-images.githubusercontent.com/35685146/36206835-9e738774-11b5-11e8-8d6c-d53cc2d1cfbb.png)

**Comment by ZarshaB** [comment]
34>> After login complete page does not appear.
![image](https://user-images.githubusercontent.com/35685146/36472796-ac3572fa-1714-11e8-848f-aedd8536a32a.png)
![image](https://user-images.githubusercontent.com/35685146/36472869-d562e9e6-1714-11e8-80cd-86799aee06c1.png)
![image](https://user-images.githubusercontent.com/35685146/36472920-f47ffa6c-1714-11e8-80e7-90ce7baa1dc5.png)
![image](https://user-images.githubusercontent.com/35685146/36472962-0e45799a-1715-11e8-9019-d9f9063a6dce.png)
![image](https://user-images.githubusercontent.com/35685146/36472975-16f810fc-1715-11e8-980e-a6472d4d833d.png)
![image](https://user-images.githubusercontent.com/35685146/36472991-1f39aa0a-1715-11e8-964c-3fbf9c62d87a.png)
![image](https://user-images.githubusercontent.com/35685146/36473081-5754d446-1715-11e8-8b47-e91020e48c10.png)
![image](https://user-images.githubusercontent.com/35685146/36473217-b75af1f4-1715-11e8-94cb-4f0e98cce651.png)
![image](https://user-images.githubusercontent.com/35685146/36473239-c8a7ec82-1715-11e8-891b-7576d642b970.png)

35>> Alignment Issue:
![image](https://user-images.githubusercontent.com/35685146/36472851-c8fd46d8-1714-11e8-897d-965542715265.png)

36>> After login complete slider does not appear.
![image](https://user-images.githubusercontent.com/35685146/36472896-e7e38ddc-1714-11e8-881a-d90302374c47.png)

37>> Images become so small it should be according to template.
![image](https://user-images.githubusercontent.com/35685146/36473038-3bff1ba2-1715-11e8-8079-60302d9950ff.png)

Template
![image](https://user-images.githubusercontent.com/35685146/36473067-4979d93e-1715-11e8-9a38-3c51f44802bd.png)

38>> Alignment issue of My profile page.
![image](https://user-images.githubusercontent.com/35685146/36473111-718aaec6-1715-11e8-9337-55fad7ab9578.png)

39>> Images are appearing blur and also extra space on pages.
![image](https://user-images.githubusercontent.com/35685146/36473144-83b72cd2-1715-11e8-8713-e0292e01f50a.png)
![image](https://user-images.githubusercontent.com/35685146/36473162-94f969e2-1715-11e8-9287-52caccb66fe0.png)
![image](https://user-images.githubusercontent.com/35685146/36473198-ac82c806-1715-11e8-9a64-ecfd0e5bfc56.png)

40>> Reward points alignment issue:
![image](https://user-images.githubusercontent.com/35685146/36473272-de7c7ac8-1715-11e8-9262-d8823e24cda4.png)

41>> Message box is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/36473287-f233baa4-1715-11e8-9b70-066705432e9b.png)

**Comment by ZarshaB** [comment]
42>> On Landscape mode only header is appearing.

**Comment by ZarshaB** [comment]
43>> Going out of layout.
![image](https://user-images.githubusercontent.com/35685146/36474960-11798182-171b-11e8-8e20-669b8122f6cc.png)

**Comment by ZarshaB** [comment]
44>> Without Images this portion is appearing like this:
![image](https://user-images.githubusercontent.com/35685146/36474985-2150d380-171b-11e8-8804-ceaa86cce53d.png)

**Comment by ZarshaB** [comment]
45>> There is extra space below How it works video.
![image](https://user-images.githubusercontent.com/35685146/36475635-213b1656-171d-11e8-938b-2e7bb4f8b5e7.png)

**Comment by ZarshaB** [comment]
45>> Arrow has become very close to button.
![image](https://user-images.githubusercontent.com/35685146/36591824-03af2408-18b5-11e8-91da-a7496eb41537.png)

46>> On this page alignment of name and and button changes. And also heading's space of page do not have same space as other pages have.
![image](https://user-images.githubusercontent.com/35685146/36592059-04afc5d2-18b6-11e8-99e4-2091d00b5b2c.png)

47>> Pop up has different alignment of Description and Details.
![image](https://user-images.githubusercontent.com/35685146/36592097-27f9987e-18b6-11e8-9ffe-49760a68cbb7.png)

48>> Space should be same for all fields of My Profile page.
![image](https://user-images.githubusercontent.com/35685146/36592302-f203a8d0-18b6-11e8-882b-f46d44913f8c.png)

49>> Slider is having grey color and also text is overlapping. It's size is also very large.

**Comment by ZarshaB** [comment]
50>> This space should be a little less equal to spacing of between other fields.
![image](https://user-images.githubusercontent.com/35685146/36592442-a3d75c96-18b7-11e8-867c-bfa95b635162.png)

51>> Please align these headings with field.
![image](https://user-images.githubusercontent.com/35685146/36592501-d20ed882-18b7-11e8-8cef-5b4454f5942b.png)

**Comment by ZarshaB** [comment]
52>> Footer spacing should be same and also please decrease it's size a little.
![image](https://user-images.githubusercontent.com/35685146/36600521-5401854e-18d4-11e8-8dbe-5391e0052dd1.png)

**Comment by ZarshaB** [comment]
53>> Reduce spacing of heading from all pages.
![image](https://user-images.githubusercontent.com/35685146/36675703-9331d0c6-1b2b-11e8-959c-84a91f352100.png)
![image](https://user-images.githubusercontent.com/35685146/36675728-a284d910-1b2b-11e8-94a0-c76daf12a02f.png)
![image](https://user-images.githubusercontent.com/35685146/36675846-ee066566-1b2b-11e8-8d34-f65fcf73b7a1.png)


54>> "Learn More" button should have same space as "View More".
![image](https://user-images.githubusercontent.com/35685146/36675803-d67e0638-1b2b-11e8-984b-6860e682f6b5.png)
![image](https://user-images.githubusercontent.com/35685146/36675827-df218d00-1b2b-11e8-8aad-1e5a1195a225.png)

55>> Buttons of How it works should be aligned with Place your Ad and Login/Register buttons.
![image](https://user-images.githubusercontent.com/35685146/36675930-1c9c53ea-1b2c-11e8-90a1-77e756e4fb0f.png)

56>> Footer icon is appearing blur.
![image](https://user-images.githubusercontent.com/35685146/36675982-407ee688-1b2c-11e8-8e78-fae4e23f507c.png)

57>> Reduce the buttons size to half.
![image](https://user-images.githubusercontent.com/35685146/36676012-5b0d3270-1b2c-11e8-83ce-107fb8096c8b.png)

**Comment by ZarshaB** [comment]
58>> Make it's "I" small.
![image](https://user-images.githubusercontent.com/35685146/36676059-7a9abfb8-1b2c-11e8-9109-950d9f0898bd.png)

59>> This page should not be scroll able.
![image](https://user-images.githubusercontent.com/35685146/36676084-8d021a70-1b2c-11e8-8dd9-a10778e36c51.png)

**Comment by ZarshaB** [comment]
60>> Adjust FAQs icon size according to screen and also looking quite blur.
![image](https://user-images.githubusercontent.com/35685146/36676160-bbbaeb26-1b2c-11e8-945d-cd6de041c15a.png)

61>> Contact Us page's heading size and icons are not according to screen.

62>> Reduce the size of ads to 10-20% from Home page, View Cars page.

**Comment by ZarshaB** [comment]
63>> Timer got stretched in this view and also button should cover the screen.
![image](https://user-images.githubusercontent.com/35685146/36676429-7bbc86be-1b2d-11e8-8e6f-f6651364d48e.png)

**Comment by ZarshaB** [comment]
64>> Reduce all extra space from both Car Detail page and View Cars page.
![image](https://user-images.githubusercontent.com/35685146/36677937-497b3be2-1b31-11e8-82a4-b43f75ae94cc.png)

65>> Make these buttons at one line and reduce all extra space.
![image](https://user-images.githubusercontent.com/35685146/36677979-65360c68-1b31-11e8-8db0-9351bb4c43ef.png)

**Comment by ZarshaB** [comment]
66>> Remove spaces and also make fields spacing equal to as it is for Place your Ad page spacing.
![image](https://user-images.githubusercontent.com/35685146/36678097-a59a7b2c-1b31-11e8-944c-b9ca88636019.png)

**Comment by asifjans** [comment]
46>> On this page alignment of name and and button changes. And also heading's space of page do not have same space as other pages have. (Fixed)


47>> Pop up has different alignment of Description and Details. (Fixed)

48>> Space should be same for all fields of My Profile page. (Fixed)

50>> This space should be a little less equal to spacing of between other fields. (Fixed)
get latest

**Comment by asifjans** [comment]
51>> Please align these headings with field. **(Fixed)**

**Comment by asifjans** [comment]
52>> Footer spacing should be same and also please decrease it's size a little. **(Fixed)**

**Comment by ZarshaB** [comment]
Fixed and removed >> 46,47,48,50,51,52

**Comment by ZarshaB** [comment]
67>> After login it redirects me to "How it works". instead of "Our Featured Cars" section.

68>> How It works page video does not play until I play it as it plays on site.

**Comment by ZarshaB** [comment]
69>> When I open site from mobile then there appears a space between slider and menu then afterwards the space disappears.

**Comment by ZarshaB** [comment]
70>> Search field functionality is not working. I searched for AED 45 and it displayed me all cars.

**Comment by ZarshaB** [comment]
71>> Buy Car button is not working.

**Comment by ZarshaB** [comment]
72>> If I open menu and Account menu both then Account's menu does not appear.
![image](https://user-images.githubusercontent.com/35685146/36894200-687a50f2-1e2c-11e8-8717-1d291da87122.png)

**Comment by ZarshaB** [comment]
73>> On clicking on "About Us" drop down should open instead of redirecting to any other page.
![image](https://user-images.githubusercontent.com/35685146/36894245-8f457694-1e2c-11e8-9233-4bcfd8a2b12e.png)

**Comment by ZarshaB** [comment]
74>> Complete name is not appearing.
![image](https://user-images.githubusercontent.com/35685146/36894305-b793d136-1e2c-11e8-9bea-33c220d8db87.png)

**Comment by ZarshaB** [comment]
75>> Buttons alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/36894330-cb0b1026-1e2c-11e8-9baa-2a1011015c4f.png)

**Comment by ZarshaB** [comment]
76>> Please increase the height of Buy Ticket Button.
![image](https://user-images.githubusercontent.com/35685146/36896104-1ebac300-1e33-11e8-95df-963a3df1c811.png)

**Comment by ZarshaB** [comment]
77>> Button's color is orange on site.
![image](https://user-images.githubusercontent.com/35685146/36896223-9a74782e-1e33-11e8-882d-7b484b8446c5.png)

**Comment by ZarshaB** [comment]
78>> Button appears blurry from outline.
![image](https://user-images.githubusercontent.com/35685146/36896434-7e923ed8-1e34-11e8-817f-a437b0a7fd90.png)

**Comment by ZarshaB** [comment]
79>> Please also make loader at the centre of page.

**Comment by ZahidRavian** [comment]
Please test the issue and remove it from GitHub.
39>> Images are appearing blur and also extra space on pages.

**Comment by ZarshaB** [comment]
39>> Spaces from below are removed but space from above is not fixed and also images are blur.
![image](https://user-images.githubusercontent.com/35685146/36966277-135b4b0e-207e-11e8-897d-0abe563aeb4c.png)

**Comment by ZarshaB** [comment]
80>> Cart icon image is not appearing.
![image](https://user-images.githubusercontent.com/35685146/36966303-29729550-207e-11e8-9372-05b66c8ff9d6.png)

**Comment by ZarshaB** [comment]
40>> Please make cart icon and menu icon aligned.
![image](https://user-images.githubusercontent.com/35685146/36983368-01484d64-20b4-11e8-969c-5bec5821f1df.png)

**Comment by ZarshaB** [comment]
41>> Button and icons are overlapping.
![image](https://user-images.githubusercontent.com/35685146/36983416-1ef87d34-20b4-11e8-85cd-64daf0018c63.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

26. Filled radio button is appearing like this: 
39>> Images are appearing blur and also extra space on pages.
44>> Without Images this portion is appearing like this: 
53>> Reduce spacing of heading from all pages.
55>> Buttons of How it works should be aligned with Place your Ad and Login/Register buttons. 
75>> Buttons alignment is not correct. 
77>> Button's color is orange on site.
78>> Button appears blurry from outline. 
39>> Spaces from below are removed but space from above is not fixed and also images are blur.
80>> Cart icon image is not appearing.

**Comment by ZarshaB** [comment]
**Not Fixed:** 26,39,44

**Comment by ZahidRavian** [comment]
Pending issues

79>> Please also make loader at the centre of page.
76>> Please increase the height of Buy Ticket Button.
74>> Complete name is not appearing.
72>> If I open menu and Account menu both then Account's menu does not appear.
71>> Buy Car button is not working.
70>> Search field functionality is not working. I searched for AED 45 and it displayed me all cars.
69>> When I open site from mobile then there appears a space between slider and menu then afterwards the space disappears.
67>> After login it redirects me to "How it works". instead of "Our Featured Cars" section.

68>> How It works page video does not play until I play it as it plays on site.
61>> Contact Us page's heading size and icons are not according to screen.

62>> Reduce the size of ads to 10-20% from Home page, View Cars page.
60>> Adjust FAQs icon size according to screen and also looking quite blur.
49>> Slider is having grey color and also text is overlapping. It's size is also very large.
44>> Without Images this portion is appearing like this:
39>> Images are appearing blur and also extra space on pages.
37>> Images become so small it should be according to template.
33>> Email template is appearing stretched on mobile. And also on clicking on link the page that appears has so much extra space on mobile.
26>> Filled radio button is appearing like this:
High Priority
10) All the pages where I have to type something like Upload Ad and Login/Register pages, on clicking on field it hides the field. Like this:
5: It is not scrollable. I have to click in order to select the price.

**Comment by ZarshaB** [comment]
42>> On these pages menu icon size becomes very small.
![image](https://user-images.githubusercontent.com/35685146/37027804-349e6f7c-2154-11e8-82b6-fa5926b6eacb.png)

**Comment by ZarshaB** [comment]
43>> Extra space on these pages.
![image](https://user-images.githubusercontent.com/35685146/37027895-7ec14408-2154-11e8-933e-2f4ce626d759.png)
![image](https://user-images.githubusercontent.com/35685146/37027898-84b269d2-2154-11e8-8bf1-380aa7e98302.png)
![image](https://user-images.githubusercontent.com/35685146/37027927-95555416-2154-11e8-8388-8680faa77629.png)

**Comment by ZarshaB** [comment]
44>> Please also reduce this space.
![image](https://user-images.githubusercontent.com/35685146/37028219-7f9f4810-2155-11e8-85a5-31e33422d050.png)

**Comment by ZarshaB** [comment]
45>> Spacing is not same.
![image](https://user-images.githubusercontent.com/35685146/37028425-07c87f86-2156-11e8-90c1-ac97ed9cb390.png)

**Comment by ZarshaB** [comment]
46>> The table should appear complete as it appears for My Ads.
![image](https://user-images.githubusercontent.com/35685146/37028886-687ba88e-2157-11e8-9092-62b33224d149.png)
![image](https://user-images.githubusercontent.com/35685146/37028933-87fb44d0-2157-11e8-9400-fd6a8b4b937c.png)
![image](https://user-images.githubusercontent.com/35685146/37028945-929a131c-2157-11e8-9cdb-00fa49881397.png)


**For this page it is correct.**
![image](https://user-images.githubusercontent.com/35685146/37028902-77708634-2157-11e8-8135-bed931193ba1.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

41>> Button and icons are overlapping.
40>> Please make cart icon and menu icon aligned from below.
39>> The menu would be like this having no space above:
76>> Please increase the height of Buy Ticket Button.

**Comment by ZarshaB** [comment]
Not Fixed >> 39>> Images are still blur.

**Comment by ZarshaB** [comment]
**Fixed:**
42,43,44,45,46,74
**Not Fixed**
37>> Images are very small. Please make it as discussed Anum.

**Comment by ZarshaB** [comment]
39>> Images are still blur.
![image](https://user-images.githubusercontent.com/35685146/37081543-91212ee4-220b-11e8-88d4-0bae3bd07fb2.png)

**Comment by asifjans** [comment]
79>> Please also make loader at the centre of page. **(Fixed)**

**Comment by asifjans** [comment]
69>> When I open site from mobile then there appears a space between slider and menu then afterwards the space disappears **(Fixed)**

**Comment by ZarshaB** [comment]
80>> Text of "Login with Facebook" is blur.
![image](https://user-images.githubusercontent.com/35685146/37088378-f5f498c0-221e-11e8-9c67-5956ba67c9bd.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

5>> It is not scroll-able. I have to click in order to select the price.
37>> Images are very small. Please make it as discussed.

**Comment by ZarshaB** [comment]
Not Fixed:
13,68 
67>> It is now taking me here after login.
![image](https://user-images.githubusercontent.com/35685146/37142080-d176f654-22d8-11e8-9d2d-a4c808af4d9a.png)

**Comment by ZarshaB** [comment]
81>> Buy Car button does not fill on click.

**Comment by ZarshaB** [comment]
82>> Footer's Alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/37147808-fa3ab8c6-22e9-11e8-86b7-84fbadd188a5.png)

**Comment by ZarshaB** [comment]
83>> Extra space is there on this page.
![image](https://user-images.githubusercontent.com/35685146/37154323-695df878-2301-11e8-8a97-cb92b5eeaa57.png)

**Comment by ZarshaB** [comment]
84>> Please reduce these spacing.
![image](https://user-images.githubusercontent.com/35685146/37154388-a5af141a-2301-11e8-947b-2bd865c1c272.png)

**Comment by ZarshaB** [comment]
85>> Alignment of maximum price.
![image](https://user-images.githubusercontent.com/35685146/37154935-563e0db2-2303-11e8-8a65-618dc0b96b47.png)

**Comment by ZarshaB** [comment]
86>> Spacing of  headings of all pages from above is not same.

**Comment by ZarshaB** [comment]
87>> When I load any page then it's header appears blank and then appears.

**Comment by asifjans** [comment]
13) It does not allow to choose from gallery. **(Fixed)**
44>> Without Images this portion is appearing like this: **(Fixed)**
62>> Reduce the size of ads to 10-20% from Home page, View Cars page. **(Fixed)**
79>> Please also make loader at the centre of page. **(Fixed)**
67>> After login it redirects me to "How it works". instead of "Our Featured Cars" section. **(Fixed)**

**Comment by ZarshaB** [comment]
**Not Fixed**
10>> It is fixed for Register, Login pages. But Not For place your Ad general portion,Order summary page.
11.44.79,67

**Comment by ZarshaB** [comment]
88>> Complete price is not displaying.
![image](https://user-images.githubusercontent.com/35685146/37281097-ad0efdac-2611-11e8-8d57-b78404c50459.png)

**Comment by ZarshaB** [comment]
89>> Timer in this view is covering the whole image.
![image](https://user-images.githubusercontent.com/35685146/37281128-ccbc11bc-2611-11e8-942a-a4f48226b11d.png)

**Comment by ZarshaB** [comment]
90>> Only text is clickable but icons are not clickable.
![image](https://user-images.githubusercontent.com/35685146/37589083-f6e3b994-2b85-11e8-861c-0ccb6e2b2cc8.png)

**Comment by ZarshaB** [comment]
**Low Priority**
31>> Cross icon for first image is appearing like this.  **(FIXED)**
![image](https://user-images.githubusercontent.com/35685146/37826199-51664248-2eb4-11e8-83a4-e137e403956b.png)

**Comment by ZarshaB** [comment]
87>> Please reduce more space. **(Low Priority)**
![image](https://user-images.githubusercontent.com/35685146/37602572-6f5d16cc-2bae-11e8-9f72-fb7709a7bbc6.png)

88>> It is not fixed for "Description" of Place your Ad. **( Low priority)** 
And for when I click on Reward points and then scroll down then it appears like this. 
![image](https://user-images.githubusercontent.com/35685146/37826337-ce0457cc-2eb4-11e8-9335-e4a16e131833.png)

**Comment by ZarshaB** [comment]
89>> Cross icon for first image is appearing like this.  **(FIXED)**
![image](https://user-images.githubusercontent.com/35685146/37826199-51664248-2eb4-11e8-83a4-e137e403956b.png)

**Comment by ZarshaB** [comment]
92>> When I click on cross sign of "Watch" pop up then it changes it's shape while loading.

**Comment by Anum444** [comment]
92>> When I click on cross sign of "Watch" pop up then it changes it's shape while loading. **(Fixed)**

**Comment by shayanr262** [comment]
26>>**(Not Fixed)**

**Comment by asifjans** [comment]
26) @shayanr262  while comment on any issue, Please   insert latest Screenshot to avoid the confusion.
