### ISSUE TITLE
UI - Tasks

### ISSUE THREAD

**Issue by asifjans** [asifjans/Inovedia#91]
@ZarshaB  Please list down task related to UI

**Comment by ZarshaB** [comment]
**Home:**
1 >> Color is changed. 
![image](https://user-images.githubusercontent.com/35685146/36106029-0201d914-1038-11e8-9019-4827bac14288.png)

2>>  Learn More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
3>>  Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
5 >> Drop down is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/35802294-580cf476-0a91-11e8-9e7b-9974f54268e3.png)

6>> Header Jerks.

7>> Alignment is correct but It's size has become very small.
![image](https://user-images.githubusercontent.com/35685146/35856873-1df823dc-0b59-11e8-96d4-5853d95fb2d1.png)

**Comment by ZarshaB** [comment]
**View Cars** 
**Not Fixed:**

2>> Space is reduced for minutes .Please also remove it for Hours in Car detail page and pop ups.
![image](https://user-images.githubusercontent.com/35685146/35968495-d9b33bf6-0ce5-11e8-9d77-6e4ad9e129e7.png)


Template:
![image](https://user-images.githubusercontent.com/35685146/35861540-ea601910-0b69-11e8-86ea-282640a40bfb.png)

3>>Line is removed that is okay. Please also reduce some space for AED.
![image](https://user-images.githubusercontent.com/35685146/36089688-022be72e-0fff-11e8-9cbc-35e3d8224cf0.png)


On Home Page:
![image](https://user-images.githubusercontent.com/35685146/35861864-71068d9a-0b6b-11e8-8fe2-07f7f6990539.png)


5>> It should have same font color and bold  as it has for "Search Filter".
![image](https://user-images.githubusercontent.com/35685146/36157601-f3926550-10fb-11e8-80dd-d90a1430b374.png)

**Comment by ZarshaB** [comment]
**Car Detail
Not Fixed:**


2 >> Alignment is not correct.
![image](https://user-images.githubusercontent.com/35685146/35861407-67f10dcc-0b69-11e8-9b0c-a63157baaf92.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/35861441-8bab070e-0b69-11e8-916a-ad729da9273f.png)

3>> Heading and filter should be at same level as it is in template.
![image](https://user-images.githubusercontent.com/35685146/36157453-a61370c6-10fb-11e8-9d48-f080905959d9.png)


**Template:**
![image](https://user-images.githubusercontent.com/35685146/36157423-91d215e0-10fb-11e8-85cf-4ea724b5c042.png)

**Comment by ZarshaB** [comment]
**Not Fixed:**
**Order Summary:**


3>>  Checkout button should not turn to green on clicking, it should have same effect as other buttons have.

5>>  For long title, complete quantity is not appearing in field.
![image](https://user-images.githubusercontent.com/35685146/35911361-71e239ca-0c1b-11e8-9cf2-9300dd72fa28.png)


7>> Color is not green as it is used on site.
![image](https://user-images.githubusercontent.com/35685146/36091804-e08569f8-1006-11e8-8c84-aefa14fdc323.png)

**Comment by ZarshaB** [comment]
**Register Page**

**Label**

19>> Please change placeholder to "Confirm Password" .
![image](https://user-images.githubusercontent.com/35685146/36144771-fce1a42a-10d0-11e8-8590-9a4cb78ed932.png)

**Comment by ZarshaB** [comment]
**Order Confirmation Email Template:**
Please move "Paid" stamp to left and make space between highlighted line.
![image](https://user-images.githubusercontent.com/35685146/36139802-ca21faf4-10c0-11e8-834e-1609723f4417.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/36139812-d3811986-10c0-11e8-8bb2-4f81e0afe549.png)

Email Templates:
Please change it to "onto" instead of "on to" in both "Reset password" and "Verify your Account" template.
![image](https://user-images.githubusercontent.com/35685146/36145254-a034f338-10d2-11e8-90b8-085b05e612b8.png)

**Comment by ZarshaB** [comment]
On selected page menu should be highlighted like this.
![image](https://user-images.githubusercontent.com/35685146/36062336-45009668-0e8c-11e8-99ca-3fb06a068c82.png)

**Comment by ZarshaB** [comment]
**My Account**
1) It should start from How it works and end at Place your Ad button. Active option should be highlighted according to template.
![image](https://user-images.githubusercontent.com/35685146/36153851-747b66c2-10f1-11e8-8193-614e1ee06617.png)

**Comment by ZarshaB** [comment]
e-ticket:

1) It is missing ticket number,watermark, full name will come. Mobile number will contain +971 at start, ticket price will have AED, reduce space for Car details. Below text will be center aligned.
![image](https://user-images.githubusercontent.com/35685146/36147838-96f0a7e6-10db-11e8-8f44-5350f9fc829a.png)

**Comment by ZarshaB** [comment]
**My Profile:**

16) Please remove time from DOB.
![image](https://user-images.githubusercontent.com/35685146/36100481-3959aeec-1028-11e8-99b4-66cf52c86aec.png)

**Comment by ZarshaB** [comment]
**Contact Us:**
4) Please make spacing same as Template.
![image](https://user-images.githubusercontent.com/35685146/36154372-13e62e3a-10f3-11e8-9df0-8a4b471eae4a.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36154395-1fd56530-10f3-11e8-9621-b4fe6cc369b3.png)

**Comment by ZarshaB** [comment]
**Place your Ad:**
2) There should be comma after name.
![image](https://user-images.githubusercontent.com/35685146/36147063-95b6fa4a-10d8-11e8-9c39-d524b06ad7f9.png)

**Comment by ZarshaB** [comment]
**My Ads:**

35>> Alignment is not correct.

![image](https://user-images.githubusercontent.com/35685146/36197941-1c7746de-1197-11e8-8174-9f0b81e558c1.png)

**Comment by ZarshaB** [comment]
**Home**
36>> Buttons have changed.
![image](https://user-images.githubusercontent.com/35685146/36198435-6ff0d176-1198-11e8-8d77-6c0dfb36e55f.png)

37>> When Item is added to Favourites then on Home page images disappears and on View Cars page layout changes on clicking on "Ok" button of pop up.

**Comment by ZarshaB** [comment]
**Order Summary Page:**
Color of field highlight should be same as it is on Register page.
![image](https://user-images.githubusercontent.com/35685146/36198608-dd10ed22-1198-11e8-8ba7-f0720c03012b.png)

**Comment by ZarshaB** [comment]
40>> Both spacing should be same.
![image](https://user-images.githubusercontent.com/35685146/36198906-bf969de0-1199-11e8-8c3b-e0a53efc8321.png)

**Comment by ZarshaB** [comment]
Responsive Issues= https://github.com/asifjans/Inovedia/issues/61

**Comment by ZarshaB** [comment]
**Contact Us**
41>> Please make it "Please select City" as user does not know what this drop down is about.
![image](https://user-images.githubusercontent.com/35685146/36206200-53ce88d8-11b3-11e8-8ff5-e875680ff04d.png)

**Comment by ZarshaB** [comment]
42>> Spacing on all pages from upwards and downwards should be same.
![image](https://user-images.githubusercontent.com/35685146/36210386-1c8cebd2-11c0-11e8-9add-b948ce9738a7.png)

**Comment by ZarshaB** [comment]
43>> Both buttons should have same spacing as on other pages.
![image](https://user-images.githubusercontent.com/35685146/36210569-8ec4820a-11c0-11e8-95de-b17124b3e4ee.png)

**Comment by ZarshaB** [comment]
44>> This pop up and cross icon should be same as other pop ups.
![image](https://user-images.githubusercontent.com/35685146/36210627-bb0c68f0-11c0-11e8-9492-b7e80d5b2cd6.png)

**Comment by ZarshaB** [comment]
45>> This image should also not appear as stretched.
![image](https://user-images.githubusercontent.com/35685146/36210682-e42bdefa-11c0-11e8-8a94-9d7d70ff27fc.png)

**Comment by ZarshaB** [comment]
**High Priority**
2,3,6,8,9,10,11,15,21,23,28,31,32,33,35,36,37,42,43,44,45

**Comment by ZarshaB** [comment]
46>> Spacing of fields Car make, model, city, price and color should be same as spacing of below fields of this page.
![image](https://user-images.githubusercontent.com/35685146/36211449-131a5cf8-11c3-11e8-975d-bef1c18e9e10.png)

**Comment by ZarshaB** [comment]
47>> Footer icons and text should have same spacing from upwards and downwards.
![image](https://user-images.githubusercontent.com/35685146/36211569-66e0a590-11c3-11e8-89fc-cb315cc68f67.png)

**Comment by ZarshaB** [comment]
High Priority
2,3,6,8,9,10,11,15,21,23,28,31,32,33,35,36,37,42,43,44,45,46

**Comment by ZahidRavian** [comment]
**Following issues are fixed and ready for testing.**

1 >> Color is changed.
2>> Learn More buttons and "Powered by Inovedia" should be aligned to "Place your Ad" buttons.
3>> Left Alignment of Images ( How it works) , Testimonials and social icons should be aligned.
4 >> Drop down is going out of layout.
5>> Header Jerks.
6>> Alignment is correct but It's size has become very small.
7>> Please remove this line from logo. It should be same as it is from downwards
8>> Search field should be in center. "Search" text should have same font, boldness and hover effect as it is for "Login/Register" button.
13>> It should have same font color and bold as it has for "Search Filter".
15>> Alignment is not correct
16>> Heading and filter should be at same level as it is in template.
17>> Checkout button should not turn to green on clicking, it should have same effect as other buttons have.
18>> For long title, complete quantity is not appearing in field.
19>> Message would be:
20>> Please change placeholder to "Confirm Password" .
21>> Gender will appear in one line.
22>> Alignment of both boxes is not same.
23>> Please change the alignment of captcha to right and of check boxes to left.
31>> Please remove time from DOB.
32>> All pages' headings space should be same. Also "Our Featured Cars" and "How it works" heading should have same space.
34>> There should be comma after name.
35>> Alignment is not correct.
41>> Please make it "Please select City" as user does not know what this drop down is about.

**Comment by ZarshaB** [comment]
**Fixed**
1,2,3,5,6,8,10,1516,,20,21,25,31,34,35,41

**Not Fixed**
7,9,17,
13>> Font color should be same grey as we are using in the site.
![image](https://user-images.githubusercontent.com/35685146/36248059-fd727c56-1257-11e8-8b7b-4a738aa7e016.png)

**Comment by ZarshaB** [comment]
**Purchase Car**
50>> Decrease the title of Car to remove extra spacing.
![image](https://user-images.githubusercontent.com/35685146/36249294-fcaa72d4-125b-11e8-9283-f36f13cc21d4.png)

**Comment by ZarshaB** [comment]
**Contact Us**
29>> Message field is a required field.
30>> Pop up message that will appear on submitting form is:
**Hi  (Name),
Thanks for reaching out. We’ll get back to you within 12 working hours.**
Instead of:
![image](https://user-images.githubusercontent.com/35685146/36145628-be8e506c-10d3-11e8-9804-81779a4e2a55.png)
31>> On submitting of form he'll get an email:
**Hi  (Name),
Thanks for reaching out. We’ll get back to you within 12 working hours.
In the meantime, why don’t you try your luck for your next ride here. [link to View Cars will be displayed as “here”]
Go get ’em tiger!!!**

**Comment by ZarshaB** [comment]
54>> Message is not correct. It would be "Please choose an Image.." instead of "Please Choose a Image.."
![image](https://user-images.githubusercontent.com/35685146/36251786-429ca0b6-1264-11e8-895b-d7f9d401b39b.png)

**Comment by ZahidRavian** [comment]
**Following issues are fixed and ready for testing.**

11>> Space is reduced for minutes .Please also remove it for Hours in Car detail page and pop ups.
13>> Font color should be same grey as we are using in the site.
28>> It should start from How it works and end at Place your Ad button. Active option should be highlighted according to template.
32>> All pages' headings space should be same. Also "Our Featured Cars" and "How it works" heading should have same space.
33>> Please make spacing same as Template.
42>> Spacing on all pages of My Account from upwards and downwards should be same.
44>> This pop up and cross icon should be same as other pop ups.
46>> Spacing of fields Car make, model, city, price and color should be same as spacing of below fields of this page.
48>> Both spacing should be same.
54>> Message is not correct. It would be "Please choose an Image.." instead of "Please Choose a Image.."

**Comment by ZarshaB** [comment]
55>> It should be fixed below.
![image](https://user-images.githubusercontent.com/35685146/36263312-c4895aa2-128b-11e8-959c-12e20e70fcfe.png)

**56>> On clicking on "Watch" from anywhere it displays me this.
![image](https://user-images.githubusercontent.com/35685146/36263343-dc1eadc0-128b-11e8-82e1-ca919fece662.png)**

57>> On every page logo takes time to load. Page loads and then logo loads.

58>> Please also make this spacing equal to Timer's spacing.
![image](https://user-images.githubusercontent.com/35685146/36263516-32bc6910-128c-11e8-9741-861888429d0f.png)

59>> When I add item from 2nd page of View Cars to Favourites then it takes me to 1st page and also filters get filled with details of that car.
![image](https://user-images.githubusercontent.com/35685146/36263720-a241232a-128c-11e8-9eef-3ac29abb2deb.png)

60>> Box is not aligned with update and remove.
![image](https://user-images.githubusercontent.com/35685146/36263816-de782f82-128c-11e8-84b2-1660a29111c7.png)

61>> Please reduce title in Car name field of Purchase History so that spacing could be removed. And Latest bought item should appear above not at the last.
![image](https://user-images.githubusercontent.com/35685146/36264205-f25ffb82-128d-11e8-93c9-a732ee604c5e.png)

62>> Please also make it in one line.
![image](https://user-images.githubusercontent.com/35685146/36264270-1fdccce8-128e-11e8-9263-b9dd3990ee9e.png)

63>> Email disappears.
![image](https://user-images.githubusercontent.com/35685146/36264524-c9b0f4d8-128e-11e8-9247-1a2d158c39dd.png)

64>> Please remove highlighted lines.
![image](https://user-images.githubusercontent.com/35685146/36264567-df75843c-128e-11e8-8e69-4bed64f823c5.png)

**Comment by ZarshaB** [comment]
**Fixed Issues:**
11,13,32,33,42,44,45,46,48,54

**Comment by ZarshaB** [comment]
65>> These error are overlapping.
![image](https://user-images.githubusercontent.com/35685146/36265642-7b6b7264-1291-11e8-8ea0-6b363a09fb04.png)
66>> Reset Password, Live Ad, Order Summary Templates font is appearing blue.
67>> I'm able to edit DOB.
![image](https://user-images.githubusercontent.com/35685146/36266589-9fb58c70-1293-11e8-9f6f-0c51697eb734.png)

**Comment by ZarshaB** [comment]
68>> This message should appear with scrolling down and remove extra space.
![image](https://user-images.githubusercontent.com/35685146/36266735-04d0c462-1294-11e8-9909-c143b05bb720.png)

**Comment by ZahidRavian** [comment]
**These issues are fixed and ready for testing.**

17>> Checkout button should not turn to green on clicking, it should have same effect as other buttons have.
18>> For long title, complete quantity is not appearing in field.
19> pop up for Unsuccessful Transaction:
22>> Alignment of both boxes is not same.
28>> It should start from How it works and end at Place your Ad button. Active option should be highlighted according to template.
33>> Please make spacing same as Template.
36>> Buttons of Buyer and Seller have changed. It should be by default selected Buyer. Selected should be filled and bold. Not selected should be unfilled and semi bold. And it should not become unfilled on clicking anywhere else other than buttons.
38>> Color of field highlight should be same as it is on Register page.
39>> By Default the name of field should be "Please select from city" as it is on Register page.
43>> Both buttons should have same spacing as on other pages.
44>> This pop up and cross icon should be same as other pop ups.
45 >> Video should have play, pause etc. buttons.
47>> Footer icons and text should have same spacing from upwards and downwards.
58>> Please also make this spacing equal to Timer's spacing.
64>> Please remove highlighted lines.
65>> These error are overlapping.

**Comment by ZarshaB** [comment]
69>> Buyer and Seller's functionality is fixed. But please also change buttons as they were before.
![image](https://user-images.githubusercontent.com/35685146/36298481-2c17c314-131a-11e8-9e12-ead9d31ec033.png)

**Template**
![image](https://user-images.githubusercontent.com/35685146/36298489-37eabbf6-131a-11e8-8731-1f7c3528feb1.png)

70>> Spacing is not correct. Please make it same as it is on Register page.
![image](https://user-images.githubusercontent.com/35685146/36298900-4b86f6aa-131c-11e8-9066-78aecfba965a.png)

71>> Please make it's U capital.
![image](https://user-images.githubusercontent.com/35685146/36299113-5c4fbb60-131d-11e8-9389-4d9c0bf61dc4.png)

72>> Colors are changed for Reset template:
![image](https://user-images.githubusercontent.com/35685146/36299185-b506c622-131d-11e8-9e65-8a11b11d34f2.png)

73>> Please make the subject as "Buy Car Request".
![image](https://user-images.githubusercontent.com/35685146/36299253-fb1faf66-131d-11e8-8928-e9e619a03aa7.png)

74>> Please make it weladela.com.
![image](https://user-images.githubusercontent.com/35685146/36299546-52f2f134-131f-11e8-8811-3f1c9080b6c5.png)

75>> No space between mobile code and number. Empty Color and Reference number has UI issues. And missing water mark.
![image](https://user-images.githubusercontent.com/35685146/36299621-aed10c2a-131f-11e8-89b2-0ce0daea0b55.png)

76>> Spacing of Testimonials, Our Featured Cars and How it works is not updated.

**Comment by ZarshaB** [comment]
**Fixed** 
17,22,33,36,38,39,43,44,45,47,58,64,65
**Not Fixed**
18,28

**Comment by ZarshaB** [comment]
77>> Status of Ad on My Ads would be:
 Ad Live, Car Sold and Ad Removed.

**Comment by ZahidRavian** [comment]
**Pending issues are**

14>> Please reduce spacing.
24>> When I click on "Next" after giving title then on next page it displays error on all required fields. It should only display error if I click on "Next" button without filling required fields.
28>> It should start from How it works and end at Place your Ad button. Active option should be highlighted according to template.
29>> Icons are appearing stretched.
50>> Decrease the title of Car to remove extra spacing.
56>> On clicking on "Watch" from anywhere it displays me this.
59>> When I add item from 2nd page of View Cars to Favourites then it takes me to 1st page and also filters get filled with details of that car.
60>> Box is not aligned with update and remove.
61>> Latest bought item should appear above not at the last.
63>> Email disappears.
67>> I'm able to edit DOB.
68>> This message should appear with scrolling down and remove extra space.
69>> Buyer and Seller's functionality is fixed. But please also change buttons as they were before.
70>> Spacing is not correct. Please make it same as it is on Register page.
71>> Please make it's U capital. (Fixed)
72>> Colors are changed for Reset template:
73>> Please make the subject as "Buy Car Request". (Fixed)
74>> Please make it weladela.com.
75>> No space between mobile code and number. Empty Color and Reference number has UI issues. And missing water mark.
76>> Spacing of Testimonials, Our Featured Cars and How it works is not updated. (Fixe)
77>> Status of Ad on My Ads would be: (Fixed)

**Comment by ZarshaB** [comment]
78>> The loader is changed when I click on Delete option of My Ads. It should be same as for all pages.
![image](https://user-images.githubusercontent.com/35685146/36302978-4653a7cc-132c-11e8-9f9b-d5f77ebd1b1c.png)

**Comment by ZarshaB** [comment]
**Low Priority**
79>> Please make the size same as the size of loader.
![image](https://user-images.githubusercontent.com/35685146/36303070-9aed9a86-132c-11e8-9bf8-161228f5a40f.png)

**Comment by ZarshaB** [comment]
80>> When I click on Favourites from Home page then whole page's layout changes.

**Comment by ZarshaB** [comment]
81>> Please remove "Okay" from this pop up.
![image](https://user-images.githubusercontent.com/35685146/36303141-e1b23274-132c-11e8-99eb-422d4236816d.png)

**Comment by ZarshaB** [comment]
82>> It should have play button at centre as we have for you tube's videos.
![image](https://user-images.githubusercontent.com/35685146/36303181-091c8710-132d-11e8-83cf-945f615f5864.png)

**Comment by ZarshaB** [comment]
83>>Details and Description palcement has changed.
![image](https://user-images.githubusercontent.com/35685146/36303925-a89ad9c0-132f-11e8-946f-ec33c7fe3da8.png)

**Comment by ZarshaB** [comment]
84>> Please decrease it's space.
![image](https://user-images.githubusercontent.com/35685146/36303994-e898fa2a-132f-11e8-9e8e-59a58a232658.png)

**Comment by asifjans** [comment]
69>> Buyer and Seller's functionality is fixed. But please also change buttons as they were before. (Fixed)

**Comment by ZarshaB** [comment]
83>> I'm unable to click on "Send" button.
![image](https://user-images.githubusercontent.com/35685146/36315915-b2e553f8-135a-11e8-9feb-2b7c275b5f95.png)

**Comment by ZarshaB** [comment]
84>> My images are not appearing on Home page and also when I ad ad to my featured car then still image doe snot appear there.
![image](https://user-images.githubusercontent.com/35685146/36316002-ebaa7920-135a-11e8-879c-572c58a09f1a.png)

**Comment by ZarshaB** [comment]
87>> Drop down is Overlapping.
![image](https://user-images.githubusercontent.com/35685146/36316503-50081674-135c-11e8-887f-e59bbbdabe6c.png)

**Comment by ZahidRavian** [comment]
**These issues are fixed and ready for testing**

29>> Icons are appearing blur.
50>> Decrease the title of Car to remove extra spacing.
60>> Box is not aligned with update and remove.
61>> Latest bought item should appear above not at the last.
63>> Email disappears.
67>> I'm able to edit DOB.
68>> This message should appear with scrolling down and remove extra space.
69>> Buyer and Seller's functionality is fixed. But please also change buttons as they were before.
70>> Spacing is not correct. Please make it same as it is on Register page.
72>> Colors are changed for Reset template:
73>> Please make the subject as "Buy Car Request".
74>> Please make it weladela.com.
77>> Status of Ad on My Ads would be: Ad Live, Car Sold and Ad Removed.
78>> The loader is changed when I click on Delete option of My Ads. It should be same as for all pages.
79>> Please make the size same as the size of loader.
82>> It should have play button at centre as we have for you tube's videos.
85>> I'm unable to click on "Send" button.
86>> My images are not appearing on Home page and also when I ad ad to my featured car then still image doe snot appear there.
87>> Drop down is Overlapping.

Pending issues are 
75>> No space between mobile code and number. Empty Color and Reference number has UI issues. And missing water mark.
59>> When I add item from 2nd page of View Cars to Favorites then it takes me to 1st page and also filters get filled with details of that car.

**Comment by ZarshaB** [comment]
**Spacing of All message pages is not equal.**
![image](https://user-images.githubusercontent.com/35685146/36367415-66dbec12-1574-11e8-9786-0311777ad79f.png)
![image](https://user-images.githubusercontent.com/35685146/36367471-97b1151a-1574-11e8-8937-b7ef7910d386.png)
![image](https://user-images.githubusercontent.com/35685146/36367496-b13afec4-1574-11e8-97df-945cc99d2a5c.png)
![image](https://user-images.githubusercontent.com/35685146/36367548-fe5a0e52-1574-11e8-891f-db59d46b7c3d.png)
![image](https://user-images.githubusercontent.com/35685146/36367604-408b0a2e-1575-11e8-9b61-39929bb7423e.png)

**Comment by ZarshaB** [comment]
89>> Space is not equal.
![image](https://user-images.githubusercontent.com/35685146/36368162-d3a29d16-1577-11e8-921a-cefbf8ae8fe1.png)

90>> Menu Highlight is appearing like this on scrolling down.
![image](https://user-images.githubusercontent.com/35685146/36368228-1053322a-1578-11e8-84bf-8c585b39cfb0.png)

**Comment by ZarshaB** [comment]
90>> If Reward points are lower than Ticket Price then Pop-up will be displayed with redeem points terms.

**Comment by ZarshaB** [comment]
91>> All buttons should have same size as it is for "View Ad".
![image](https://user-images.githubusercontent.com/35685146/36369168-09909208-157c-11e8-885c-db35fc18cd54.png)
![image](https://user-images.githubusercontent.com/35685146/36369227-4a0fddca-157c-11e8-858c-709a1d938eea.png)
![image](https://user-images.githubusercontent.com/35685146/36369263-7831a580-157c-11e8-96b5-b4308bd19781.png)

**Comment by ZarshaB** [comment]
92>> These both boxes are not starting and ending at same point.
![image](https://user-images.githubusercontent.com/35685146/36369860-b1f19580-157e-11e8-9c94-685eea4eaed1.png)
![image](https://user-images.githubusercontent.com/35685146/36369880-bec4f1d0-157e-11e8-925f-f338a984cd9d.png)

**Comment by ZarshaB** [comment]
93>> About Us >> Terms and Conditions , Privacy Policy 
Footer Layout Issue
![image](https://user-images.githubusercontent.com/35685146/36370728-9214e2fa-1581-11e8-8ba4-0e537ff32baf.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing.**

88>> Spacing of All message pages is not equal.
89>> Space is not equal.
90>> Menu Highlight is appearing like this on scrolling down.
92>> These both boxes are not starting and ending at same point.
High Priority
93>> About Us >> Terms and Conditions , Privacy Policy
Terms and Conditions--Links Footer Layout Issue

**Comment by ZarshaB** [comment]
94>> Please make its "I" small.
![image](https://user-images.githubusercontent.com/35685146/36379596-0cef6094-15a1-11e8-95ff-07717726e81a.png)

**Comment by ZarshaB** [comment]
91>> Spacing between fields is not equal.
![image](https://user-images.githubusercontent.com/35685146/36414926-d7c6649e-1645-11e8-99b8-e3c95ace7c45.png)

**Comment by ZarshaB** [comment]
92>> Order Summary template is appearing blue.
![image](https://user-images.githubusercontent.com/35685146/36419782-b9317960-1654-11e8-929e-299908269fe4.png)

**Comment by ZarshaB** [comment]
93>> Please check spacing of Heading for this page. Is it same as it is for other pages.
![image](https://user-images.githubusercontent.com/35685146/36419946-34fd30b6-1655-11e8-9a24-dc32f8a8d896.png)

**Comment by ZahidRavian** [comment]
This issue is fixed now, please take a look on it.
91>> Spacing between fields is not equal.

**Comment by ZarshaB** [comment]
94>> Please make this alignment from "y" for both Order summary and Place your Ad pages.
![image](https://user-images.githubusercontent.com/35685146/36431163-b2ec11ea-1678-11e8-9b95-3673a7114ee7.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing**

92>> Order Summary template is appearing blue.
93>> Please check spacing of Heading for this page. Is it same as it is for other pages.
94>> Please make this alignment from "y" for both Order summary and Place your Ad pages.

**Comment by ZarshaB** [comment]
92>> Mere pass abi bhi blue aa raha hai 🎃 
![image](https://user-images.githubusercontent.com/35685146/36433460-5bc2bc6a-167e-11e8-8531-44eff6f457f6.png)

**Comment by shayanr262** [comment]
hi

**Comment by ZahidRavian** [comment]
**This issue is fixed and ready for testing**

92>> Mere pass abi bhi blue aa raha hai 🎃

**Comment by ZarshaB** [comment]
1>> Please make only "Ad Live" status green and others should be of different color. For Ad Removed, Pending and Ad Live it is perfect. For Car Sold please also change color  to any other color to differentiate. 
![image](https://user-images.githubusercontent.com/35685146/36470839-1cfcb892-170e-11e8-8fe0-fd769f49e831.png)

**Comment by ZarshaB** [comment]
2>> UI issue of fields.
![image](https://user-images.githubusercontent.com/35685146/36471054-e22e43ec-170e-11e8-81ab-c51ee024fc3f.png)

**Comment by ZarshaB** [comment]
3>> "Previous" button here is not looking good now, it would look good if it's replacement is changed to right for both "Images" and "Specification" pages of "Place your Ad".
![image](https://user-images.githubusercontent.com/35685146/36471111-22e4bede-170f-11e8-8582-4856bf3c5486.png)

![image](https://user-images.githubusercontent.com/35685146/36471127-2e5b4e68-170f-11e8-9b8e-437b52b13497.png)


And also same alignment of "Cancel" button for "My Profile" page.
![image](https://user-images.githubusercontent.com/35685146/36471172-4fd4088c-170f-11e8-8865-f40e34fb5fd0.png)

**Comment by ZarshaB** [comment]
4>> Please make all these spaces equal to Service History.
![image](https://user-images.githubusercontent.com/35685146/36484492-496a6de8-173b-11e8-9c9f-1840bec9618b.png)
![image](https://user-images.githubusercontent.com/35685146/36484509-53d9e42a-173b-11e8-936b-181a0d7f8ae2.png)
![image](https://user-images.githubusercontent.com/35685146/36484515-5f04a592-173b-11e8-800b-3e43d30a4434.png)
![image](https://user-images.githubusercontent.com/35685146/36484542-7844c2b2-173b-11e8-95bf-fc10a5815950.png)

**Comment by ZarshaB** [comment]
5>> Watermark placement of ticket is not correct.
![image](https://user-images.githubusercontent.com/35685146/36529515-5ade4910-17da-11e8-967b-15032925717f.png)

**Comment by ZarshaB** [comment]
6>> This space has increased. It should be same as "Place your Ad" page.
![image](https://user-images.githubusercontent.com/35685146/36530456-e3b87948-17dc-11e8-8131-1ac33a410ff9.png)

"Place your Ad".
![image](https://user-images.githubusercontent.com/35685146/36530467-ef72f09c-17dc-11e8-800b-cdf9044567c7.png)

**Comment by sammiullah** [comment]
3>> "Previous" button here is not looking good now, it would look good if it's replacement is changed to right for both "Images" and "Specification" pages of "Place your Ad".  FIXED

And also same alignment of "Cancel" button for "My Profile" page. Fixed


And also same alignment of "Cancel" button for "My Profile" page. Fixed


5>> Watermark placement of ticket is not correct. FIXED

6>> This space has increased. It should be same as "Place your Ad" page. FIXED

"Place your Ad Buttons". FIXED

**Comment by ZarshaB** [comment]
**Fixed and Removed:**
2 , 5 

**Not Fixed:**
6 , 4 = Spaces are equal from upwards but not from downwards. (I have told Anum about it)

**Comment by ZarshaB** [comment]
7>> Please make this message "No Results found" in red, same as it is on Dubizzel and also it's font size is very small.
![image](https://user-images.githubusercontent.com/35685146/36542542-e6d49c8a-1802-11e8-9c89-b4e301efd5be.png)

![image](https://user-images.githubusercontent.com/35685146/36542556-efa44f22-1802-11e8-9687-21e09dd570c2.png)

**Comment by Anum444** [comment]
**Fixed**
6 , 4 = Spaces are equal from upwards but not from downwards. (I have told Anum about it)

**Comment by ZarshaB** [comment]
6,4 >> Fixed

**Comment by ZarshaB** [comment]
1>> Please also change title of page to "Privacy Policy".
![image](https://user-images.githubusercontent.com/35685146/36591357-92e22ab4-18b3-11e8-8482-f5e33187bd41.png)

**Comment by ZarshaB** [comment]
2>> Please make it aligned below "View Cars" and decrease it's size a little.
![image](https://user-images.githubusercontent.com/35685146/36591451-e08151b4-18b3-11e8-9620-d6cc0d8c4fa1.png)

**Comment by ZarshaB** [comment]
3>> Extra commas are here.
![image](https://user-images.githubusercontent.com/35685146/36591538-23909672-18b4-11e8-8d15-fbf65b1d9c77.png)
![image](https://user-images.githubusercontent.com/35685146/36591552-2ebb1ad6-18b4-11e8-9cef-1331f9e6e865.png)

**Comment by ZarshaB** [comment]
4>> It would be in one line.
![image](https://user-images.githubusercontent.com/35685146/36591592-4fddcf56-18b4-11e8-8249-4a6d4f35fee0.png)

5>> It does not look nice. And also if name of image is long then it would cover the whole area.
![image](https://user-images.githubusercontent.com/35685146/36591649-852147f6-18b4-11e8-9aa4-0364e7d7b1d6.png)

**Comment by ZarshaB** [comment]
6>> Please make weladela.com and WelaDela everywhere on "Privacy Policy" page.

**Comment by ZarshaB** [comment]
7>> Link is not appearing correct. Before it was okay. 
![image](https://user-images.githubusercontent.com/35685146/36661897-793fc128-1afe-11e8-974a-c978348aa582.png)
![image](https://user-images.githubusercontent.com/35685146/36661912-85b75a42-1afe-11e8-959c-2991cdc5666a.png)

**Comment by ZarshaB** [comment]
8>> All status should have same pattern. As "Pending" status has whole word capitalized. Please make only first letter capital.
![image](https://user-images.githubusercontent.com/35685146/36663502-970b2e4a-1b03-11e8-8941-8cf040e332f9.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing:**

1>> Please also change title of page to "Privacy Policy".
2>> Please make it aligned below "View Cars" and decrease it's size a little.
3>> Extra commas are here.
4>> It would be in one line.
5>>  also if name of image is long then it would cover the whole area.
6>> Please make weladela.com everywhere on "Privacy Policy" page. 
7>> Link is not appearing correct. Before it was okay. 
8>> All status should have same pattern. As "Pending" status has whole word capitalized. Please make only first letter capital.

**Comment by ZarshaB** [comment]
9>> Message of this page should have same alignment as it has for other pages.
![image](https://user-images.githubusercontent.com/35685146/36718980-87839030-1bc5-11e8-993b-baa432a6efab.png)

**Comment by ZarshaB** [comment]
6>> It is still not same. And also make it hyperlink as it is on other static pages.
![image](https://user-images.githubusercontent.com/35685146/36720195-1f4aa05e-1bc9-11e8-8e46-6a04fc627eb9.png)

**Comment by ZarshaB** [comment]
7>> It should be "Login with Facebook."
![image](https://user-images.githubusercontent.com/35685146/36721482-d73b9030-1bcc-11e8-950a-54e6769a370f.png)

**Comment by ZarshaB** [comment]
12>> For file cross icon appears at very awkward place. It should be with document as it appears for images.
![image](https://user-images.githubusercontent.com/35685146/36721694-712ff44c-1bcd-11e8-9588-2ad676894ad1.png)

**Comment by ZarshaB** [comment]
8>> Fixed for "Pending". Please also make correction for "Raffle draw". And also counter check for all statuses.

**Comment by ZarshaB** [comment]
13>> It should also be "Social media".
![image](https://user-images.githubusercontent.com/35685146/36721898-fe838c00-1bcd-11e8-8c05-254586ae4a75.png)

**Comment by ZarshaB** [comment]
**Templates**
14>> **Reset Password:**
Color is appearing purple and also getting a line on button. Please remove this.
![image](https://user-images.githubusercontent.com/35685146/36725700-f9ead68e-1bd8-11e8-943d-64f00e32662f.png)

**Welcome Email:**
Also make this link of the same color as it is for email.
![image](https://user-images.githubusercontent.com/35685146/36725743-1d142a5c-1bd9-11e8-8dc6-5fdf71868f9c.png)

**Customer Enquiry:**
There is no space at sides. Not looking good. It's alignment was correct before.
![image](https://user-images.githubusercontent.com/35685146/36725814-594fe63c-1bd9-11e8-845b-65f541392749.png)

**Reset Password:**
It alignment of link should be same as we have for "Verify Account" link.
![image](https://user-images.githubusercontent.com/35685146/36725885-98051bb8-1bd9-11e8-8dad-cf43d0e85820.png)

**Comment by ZarshaB** [comment]
15>> All alert messages should have same font size as we have for pop up which appears on clicking on "delete" of "My Ads" page.

**Comment by ZarshaB** [comment]
16>> Error message remains there even after uploading files/images and when I click on somewhere else then it goes out for both image and malkiya ownership document tabs.
![image](https://user-images.githubusercontent.com/35685146/36730291-b4bbfda8-1be8-11e8-99ac-a934fbde7ecf.png)

**Comment by ZarshaB** [comment]
17>> On Hotmail/outlook Welcome email templates are going out of layout.
![image](https://user-images.githubusercontent.com/35685146/36732596-06b64c74-1bf0-11e8-8f41-d4b8f6394317.png)

Your Ad is live template is half cut.
![image](https://user-images.githubusercontent.com/35685146/36732649-25773ccc-1bf0-11e8-97a9-0d96a6e83a05.png)

**Comment by ZarshaB** [comment]
18>> Footer icons and cart icon is appearing blurry.
![image](https://user-images.githubusercontent.com/35685146/36732769-7bd8144c-1bf0-11e8-9de1-2856eb83c462.png)

**Comment by ZarshaB** [comment]
19>> Please make all pop ups to centre aligned as it is in dubizel.
![image](https://user-images.githubusercontent.com/35685146/36733833-a381008c-1bf3-11e8-9d96-05847aecdab8.png)
![image](https://user-images.githubusercontent.com/35685146/36733850-b373c02e-1bf3-11e8-8405-d489bc2c8557.png)

**Comment by ZarshaB** [comment]
20>> Order summary email template has died. :(
![image](https://user-images.githubusercontent.com/35685146/36734707-21b69fdc-1bf6-11e8-939f-e56bb7d87d6a.png)

**Comment by ZarshaB** [comment]
20>> Prices are appearing in decimal. And also alignment issue for discount, order id and date.
![image](https://user-images.githubusercontent.com/35685146/36739169-1dcba632-1c01-11e8-82a8-8c64ea0ff999.png)

**Comment by asifjans** [comment]
12>>(Haider) For file cross icon appears at very awkward place. It should be with document as it appears for images. (Fixed)

**Comment by ZarshaB** [comment]
12>> The icon should be on highlighted place.
![image](https://user-images.githubusercontent.com/35685146/36776379-5f8c1c2e-1c87-11e8-8048-c63f38c19727.png)

**Comment by ZarshaB** [comment]
20>> Please check this, when I upload any file then it changes it's place and then goes to right place.
Video Link = https://www.screencast.com/t/mwjSU3Yck

**Comment by ZarshaB** [comment]
15>> Please make all other messages same to this font size and black color.
![image](https://user-images.githubusercontent.com/35685146/36780651-61ece616-1c95-11e8-8e59-d8f31ded39ca.png)

**Other messages:**
![image](https://user-images.githubusercontent.com/35685146/36780655-6661982c-1c95-11e8-9060-c0e775c22750.png)

**Comment by ZarshaB** [comment]
16>> Please remove space for error message and field.And also make labels equal to field.
![image](https://user-images.githubusercontent.com/35685146/36782123-c1396b54-1c99-11e8-9854-555c0b289947.png)
![image](https://user-images.githubusercontent.com/35685146/36782147-d77f304c-1c99-11e8-856a-6890d0b15b67.png)

**Comment by asifjans** [comment]
8>> Fixed for "Pending". Please also make correction for "Raffle draw". And also counter check for all statuses. (Fixed)
16>> Please remove space for error message and field.And also make labels equal to field. (Fixed)

**Comment by asifjans** [comment]
14 >> **Fixed**

**Comment by asifjans** [comment]
20>> **(Haider)** ( Please check this, when I upload any file then it changes it's place and then goes to right place.
Video Link = https://www.screencast.com/t/mwjSU3Yck

**Comment by ZarshaB** [comment]
**Not Fixed**
16>> Error message is fixed for both tabs but labels alignment is Fixed for Malkiya Ownership tab but not fixed for image tab.
![image](https://user-images.githubusercontent.com/35685146/36796593-b4412896-1cc7-11e8-949a-95a208b04ccd.png)

20>> Fixed for .docx extension but not for pdf files.

**Comment by ZarshaB** [comment]
**Not Fixed**
14>> Line is still appearing on button. 👎 
![image](https://user-images.githubusercontent.com/35685146/36832652-319feeb8-1d4e-11e8-8367-eabbf3a88457.png)

Images are not appearing for Welcome email.
![image](https://user-images.githubusercontent.com/35685146/36832666-4294edd6-1d4e-11e8-937d-9a74317a67ec.png)

**Comment by ZarshaB** [comment]
**Not Fixed** I can still see this issue. 
20>> Please check this, when I upload any file then it changes it's place and then goes to right place. 
Video Link = https://www.screencast.com/t/mwjSU3Yck

**Comment by ZarshaB** [comment]
**Not Fixed**
18>> **(Anum)** Footer icons and cart icon is appearing blurry.
![image](https://user-images.githubusercontent.com/35685146/36732769-7bd8144c-1bf0-11e8-9de1-2856eb83c462.png)

**Comment by ZarshaB** [comment]
18>> On clicking on link of Live Ad template it redirects to error page.
![image](https://user-images.githubusercontent.com/35685146/36833309-c6025da0-1d50-11e8-9c65-79fa759758cd.png)

**Comment by ZarshaB** [comment]
19>> It is in white. Please see the template.
![image](https://user-images.githubusercontent.com/35685146/36833909-cb7f7a04-1d52-11e8-8a24-3ac0be39192e.png)

**Template:**
![image](https://user-images.githubusercontent.com/35685146/36833947-fa072bba-1d52-11e8-8582-51140a0d512b.png)

**Comment by ZarshaB** [comment]
17>> On Outlook it is appearing different than template.
![image](https://user-images.githubusercontent.com/35685146/36833983-21aeb5ac-1d53-11e8-89c4-0c76705da870.png)

Welcome email is ruined there lol.
![image](https://user-images.githubusercontent.com/35685146/36834028-49631b1a-1d53-11e8-9b35-39821a3077a0.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
17

**Comment by ZarshaB** [comment]
23>> On clicking on "View Ad" of live template is taking to demo site.
![image](https://user-images.githubusercontent.com/35685146/36846646-4809da22-1d7d-11e8-96da-f20ff4ee781e.png)

**Comment by asifjans** [comment]
17 & 16 (Fixed)

**Comment by ZarshaB** [comment]
24>> Please change it's font and color.
![image](https://user-images.githubusercontent.com/35685146/36848214-66f90728-1d82-11e8-8c17-2e75779535f6.png)

**Comment by sammiullah** [comment]
**Ready for Testing**
19>> Verify your Account Template it is in white. Please see the template.

14>> Line is still appearing on button.
Please make all links color of templates same. Either it should be black or grey color.

**Comment by ZarshaB** [comment]
**Fixed**
17 👍 👍 

**Not Fixed** >> 16
19>> Can't check verify your account as didn't get the email :( 
14>> Can see line on button. 
![image](https://user-images.githubusercontent.com/35685146/36854945-2bedd12e-1d94-11e8-9c27-e4a718421d82.png)

**Comment by ZarshaB** [comment]
24>> Please make it hyperlink as I can't recognise that it is a link and please make it's highlighted text same as below. 
![image](https://user-images.githubusercontent.com/35685146/36892021-49b72124-1e25-11e8-86c8-7a5ae965ed48.png)


![image](https://user-images.githubusercontent.com/35685146/36891977-1ad1f852-1e25-11e8-940e-9fa75af57d34.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
14>> I can see line on Buttons. 
![image](https://user-images.githubusercontent.com/35685146/36892111-8ff9d69a-1e25-11e8-8a12-e8dab032cca7.png)

![image](https://user-images.githubusercontent.com/35685146/36892126-9bdc20c6-1e25-11e8-9865-95410b53e106.png)

**Comment by ZarshaB** [comment]
20>> Issue is fixed for other .docs extension but Same issue appears when I upload pdf file.

**Comment by ZarshaB** [comment]
16,18,24,23 >> Not Fixed

**Comment by ZarshaB** [comment]
22>> Welcome email in outlook.
![image](https://user-images.githubusercontent.com/35685146/36893516-27eb507e-1e2a-11e8-8d38-aca25779e7e6.png)

In gmail. Please also make title center aligned.
![image](https://user-images.githubusercontent.com/35685146/36893527-3ae42d22-1e2a-11e8-848e-649a07f2b93c.png)

**Comment by ZarshaB** [comment]
25>> My Ads , My Rewards Points and My Purchase History tables when empty have different alignment than other pages.
![image](https://user-images.githubusercontent.com/35685146/36894699-112bc8e2-1e2e-11e8-9d6d-cd7c7df3b09d.png)
![image](https://user-images.githubusercontent.com/35685146/36894706-1935b5e8-1e2e-11e8-9b4a-fae292fc6552.png)
![image](https://user-images.githubusercontent.com/35685146/36894716-2266fc80-1e2e-11e8-9fe5-626853dc8a9f.png)
![image](https://user-images.githubusercontent.com/35685146/36894732-2ca9a102-1e2e-11e8-9db5-466befa6caf1.png)

**Comment by ZarshaB** [comment]
26>> Please also make the links of same black color as it is for other templates.
![image](https://user-images.githubusercontent.com/35685146/36895042-3dff02ca-1e2f-11e8-870c-710bb31fb0a1.png)

**Comment by ZarshaB** [comment]
27>> Email is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/36895164-c23278e2-1e2f-11e8-8641-a47fa53625ca.png)

**Comment by ZarshaB** [comment]
28>> Icons would be aligned with the button.
![image](https://user-images.githubusercontent.com/35685146/36895634-648c4df6-1e31-11e8-868e-9dd7a5c5c4d9.png)

**Comment by ZarshaB** [comment]
29>> No space between full and screen.
![image](https://user-images.githubusercontent.com/35685146/36896191-807fcb58-1e33-11e8-809a-acb0728148de.png)

**Comment by ZarshaB** [comment]
30>> When I open the pop up the time overlaps for other ads.
![image](https://user-images.githubusercontent.com/35685146/36899919-0ec6d5e6-1e43-11e8-8c6b-236004d21eb8.png)

**Comment by ZarshaB** [comment]
31>> Please also make it's link color black. Same as other templates. 
![image](https://user-images.githubusercontent.com/35685146/36900055-8a0b7d7e-1e43-11e8-96f0-0ae697257fc3.png)

**Comment by ZarshaB** [comment]
32>> This image should be below heading.
![image](https://user-images.githubusercontent.com/35685146/36900217-37ff75ca-1e44-11e8-8a70-ff4b2dfeb693.png)

**Comment by ZarshaB** [comment]
33>> Fb Button flickers. 
Video Link = https://www.screencast.com/t/kADa7tlyp1js

**Comment by ZarshaB** [comment]
34>> Alignment of Download Our App button also changes.
![image](https://user-images.githubusercontent.com/35685146/36901518-51865e14-1e49-11e8-9c1a-0b70c42760de.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
14>> Fixed for Reset Password template but not for View Ad template.
![image](https://user-images.githubusercontent.com/35685146/36964493-a208bb80-2078-11e8-81fd-0603ca82a2df.png)

**Comment by ZarshaB** [comment]
35>> Please also underlined it.
![image](https://user-images.githubusercontent.com/35685146/36964617-08fc8d30-2079-11e8-983a-bde021f4b3d4.png)

**Comment by ZahidRavian** [comment]
Please test the issues and remove them from GitHub.
14>> I can see line on Buttons. 
24>> Please make it hyperlink as I can't recognize that it is a link and please make it's highlighted text same as below.
26>> Please also make the links of same black color as it is for other templates. 
27>> Email is going out of layout.
31>> Please also make it's link color black. Same as other templates.

**Comment by ZarshaB** [comment]
**Fixed** >> 26,27,31

**Not Fixed**
14>> It is fixed for "Reset Password" template but not for "View Ad".
24>> "here" is not hyperlinked. Text is fixed.

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

14>> It is fixed for "Reset Password" template but not for "View Ad".
23>> On clicking on "View Ad" of live template is taking to demo site. (sami)
24>> "here" is not hyperlinked. Text is correct.
25>> My Ads , My Rewards Points and My Purchase History tables when empty have different alignment than other pages. 
29>> No space between full and screen.
32>> This image should be below heading.
33>> Fb Button flickers.
34>> Alignment of Download Our App button changes on this page.
35>> Please also underlined it.

Pending issues are 
18>> (Anum) Footer icons and cart icon is appearing blurry.
30>> When I open the pop up the timer overlaps for other ads.

**Comment by ZarshaB** [comment]
36>> Please remove this overlapping line.
![image](https://user-images.githubusercontent.com/35685146/36983949-8ae8c03e-20b5-11e8-9207-bb3f2db1dba4.png)

**Comment by ZarshaB** [comment]
Fixed: 23,24,29,32,34,35,25

Not Fixed:
14>> 
![image](https://user-images.githubusercontent.com/35685146/36984516-de768b68-20b6-11e8-8efe-19bd98a8f90e.png)

**Comment by ZarshaB** [comment]
37>> This message and field should have some space.
![image](https://user-images.githubusercontent.com/35685146/37020926-711c38a4-213f-11e8-8345-1c10f4961717.png)

**Comment by ZarshaB** [comment]
38>> These fields do not have asterisk sign as other required fields have.
![image](https://user-images.githubusercontent.com/35685146/37021188-87cbf868-2140-11e8-9ea5-83ba427853ea.png)
![image](https://user-images.githubusercontent.com/35685146/37021201-92671e88-2140-11e8-874a-d630eb9215fa.png)

Like this:
![image](https://user-images.githubusercontent.com/35685146/37021209-9f079050-2140-11e8-91b2-ab3d29666967.png)

**Comment by ZarshaB** [comment]
39>> Please align these buttons with label. **(Sami)**
![image](https://user-images.githubusercontent.com/35685146/37023014-726491dc-2146-11e8-877b-409b22110932.png)

**Comment by ZarshaB** [comment]
41>> Button is different than the one provided by client. Facebook icon looks different too. Text also does not seem bold.
![image](https://user-images.githubusercontent.com/35685146/37027396-00d01f5c-2153-11e8-8eca-d250d7f7b9aa.png)

**Comment by ZarshaB** [comment]
42>> Please also make the mileage range values bold as it is for other field values.
![image](https://user-images.githubusercontent.com/35685146/37027687-dda3c9ba-2153-11e8-9f84-08f873cb23fa.png)

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

36>> Please remove this overlapping line.
37>> This message and field should have some space.
38>> These fields do not have asterisk sign as other required fields have.
39>> Please align these buttons with label.

**Comment by ZarshaB** [comment]
36,37,38,39 >> Issues are fixed and removed.

**Comment by ZarshaB** [comment]
43>> All fields and labels alignment has changed. It was fixed before.
![image](https://user-images.githubusercontent.com/35685146/37035541-b55c3f76-216e-11e8-9089-ccf8fd6e12cd.png)

**Comment by ZarshaB** [comment]
44>> Please align the labels with fields.
![image](https://user-images.githubusercontent.com/35685146/37035593-d888816c-216e-11e8-8c3e-d9a6434b15f7.png)

**Comment by ZarshaB** [comment]
45>> Cross circle is going out of layout.
![image](https://user-images.githubusercontent.com/35685146/37038575-fbdcbf4a-2176-11e8-9aa3-f868e67d0175.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing.**

41>> Button is different than the one provided by client. Facebook icon looks different too. Text also does not seem bold.
42>> Please also make the mileage range values bold as it is for other field values.
43>> All fields and labels alignment has changed. It was fixed before.
44>> Please align the labels with fields.

**Comment by ZarshaB** [comment]
**Fixed**
41,42
**Not Fixed:**
43 >> I can still see the same issue.
44>> These two labels are mixed up.
![image](https://user-images.githubusercontent.com/35685146/37079842-de1f54e2-2205-11e8-993d-9afee4e50ad3.png)

**Comment by ZarshaB** [comment]
46>> This detail icon's placement does not look nice here.
![image](https://user-images.githubusercontent.com/35685146/37082866-80d2b3b0-220f-11e8-8662-6833755ca894.png)

**Comment by ZarshaB** [comment]
47>> Fb button flickers.

**Comment by ZahidRavian** [comment]
These issues are fixed and ready for testing.

40>> Please make all labels in the middle of fields.
43>> All fields and labels alignment has changed. It was fixed before.
44>> Please align the labels with fields.

**Comment by ZarshaB** [comment]
40,43,44,45,46 >> Issues are fixed and removed.

**Comment by asifjans** [comment]
@ZarshaB  can you please take a look on it?

**Comment by ZarshaB** [comment]
1>> It is appearing printed. And when I click on field then it becomes placeholder.
![image](https://user-images.githubusercontent.com/35685146/37202848-9c9110c0-23ad-11e8-9b71-1248ded9d4e6.png)

**Comment by ZarshaB** [comment]
2>> Complete price is not appearing.
![image](https://user-images.githubusercontent.com/35685146/37202930-e1a9e48e-23ad-11e8-90d2-0caeaa3b552b.png)

**Comment by ZarshaB** [comment]
3>> Not aligned.
![image](https://user-images.githubusercontent.com/35685146/37202954-f712be22-23ad-11e8-9bc8-7fc030196c0d.png)

**Comment by ZarshaB** [comment]
4>> Please remove this extra space.
![image](https://user-images.githubusercontent.com/35685146/37203014-1c7b9580-23ae-11e8-827a-3df192445194.png)

**Comment by ZarshaB** [comment]
5>> Alignment of all messages has disturbed.
![image](https://user-images.githubusercontent.com/35685146/37203262-f4cc6644-23ae-11e8-9a23-84df5cef648e.png)
![image](https://user-images.githubusercontent.com/35685146/37203277-fb7505d2-23ae-11e8-9e54-9aeca69769a9.png)

**Comment by ZarshaB** [comment]
6>> Anum please put commas as discussed.
![image](https://user-images.githubusercontent.com/35685146/37203350-368cdf3c-23af-11e8-8f20-b379b186e233.png)

**Comment by ZarshaB** [comment]
7>> Extra space.
![image](https://user-images.githubusercontent.com/35685146/37274668-0030e12a-25ff-11e8-8745-79d62962a106.png)

**Comment by ZarshaB** [comment]
8>> Please change it's field color to orange.
![image](https://user-images.githubusercontent.com/35685146/37274722-25c65118-25ff-11e8-97d6-c2f830bfbf00.png)

**Comment by ZarshaB** [comment]
9>> It would be ticket for one.
![image](https://user-images.githubusercontent.com/35685146/37276950-1c59f584-2605-11e8-93ff-7a048e4681f9.png)

**Comment by ZarshaB** [comment]
10>> This load icon should be in the middle of page for "Place your Ad" as it is for other pages.
![image](https://user-images.githubusercontent.com/35685146/37280867-e0fb1e44-2610-11e8-8b0a-91c35b9e7b50.png)

**Comment by ZarshaB** [comment]
11>> Please make it AED 25.
![image](https://user-images.githubusercontent.com/35685146/37332935-d2fdd138-26c9-11e8-9e72-c87bea97901e.png)

**Comment by ZarshaB** [comment]
12>> Please change it to 600.
![image](https://user-images.githubusercontent.com/35685146/37332969-ee444a6c-26c9-11e8-95d8-90f95848aacc.png)

**Comment by ZarshaB** [comment]
13>> Please change it to "odds".
![image](https://user-images.githubusercontent.com/35685146/37333078-39d05796-26ca-11e8-90d3-374cc10f1775.png)

**Comment by ZarshaB** [comment]
14>> Please make labels and placeholder centre aligned. And also there is extra space below this page.
![image](https://user-images.githubusercontent.com/35685146/37333180-7a20aa4e-26ca-11e8-94ae-c8dceb361ffb.png)

**Comment by ZarshaB** [comment]
15>> Spacing should be same from above and bottom.
![image](https://user-images.githubusercontent.com/35685146/37333576-8381f1a0-26cb-11e8-85f3-4211db2a56d0.png)

**Comment by ZarshaB** [comment]
16>> Please move update button and cancel button to mentioned places.
![image](https://user-images.githubusercontent.com/35685146/37335221-c0bfdbe6-26cf-11e8-9c6a-15debd7929a4.png)

**Comment by ZarshaB** [comment]
17>> Cross icon is not same for all pop ups. It should be same for all pop ups.
![image](https://user-images.githubusercontent.com/35685146/37335449-63065510-26d0-11e8-98a6-47a231ab1b15.png)
![image](https://user-images.githubusercontent.com/35685146/37335521-94d4976e-26d0-11e8-8c31-68b8b8721bc3.png)

**Comment by ZarshaB** [comment]
18>> Now there is no border around description, as we had before.
![image](https://user-images.githubusercontent.com/35685146/37348050-ff044f52-26f4-11e8-982b-4e9959cdcc8d.png)

**Comment by ZarshaB** [comment]
19>> Please reduce it's space.
![image](https://user-images.githubusercontent.com/35685146/37407761-44145aac-27bc-11e8-9fbb-a4c72bd86a51.png)

**Comment by ZarshaB** [comment]
20>> It should be bold.
![image](https://user-images.githubusercontent.com/35685146/37409016-1fd109a8-27bf-11e8-864c-56079acd98f8.png)

**Comment by ZarshaB** [comment]
21>> As email field contains label instead of placeholder so when I click on "Login" button without filling fields then it display message "Please enter valid email." Whereas, it should display message "This field is required."
![image](https://user-images.githubusercontent.com/35685146/37530841-55be1544-295c-11e8-8114-61864e93d622.png)

**Comment by ZarshaB** [comment]
22>> In case of wrong password, it should be:
"Oops!!! Something went wrong.
Please enter correct Username and Password

Forgot Password?"
![image](https://user-images.githubusercontent.com/35685146/37642076-b2f7398c-2c3d-11e8-8a7d-5479afa088f7.png)

**Comment by ZarshaB** [comment]
24>> Spacing of "Our Featured Cars", "Testimonials", "How it Works" , Contact Us page,Place your Ad and My Account section pages headings from top and bottom is not same like other pages.

**Comment by ZarshaB** [comment]
25>> Headings should have same font black color.
![image](https://user-images.githubusercontent.com/35685146/37767717-e664b0a0-2dec-11e8-8ad5-9d51b94a48e0.png)
![image](https://user-images.githubusercontent.com/35685146/37767739-f422e7ac-2dec-11e8-9a90-3ac4c42edb71.png)
![image](https://user-images.githubusercontent.com/35685146/37767753-fe8a75c0-2dec-11e8-97a6-34aa767b09ab.png)

**Comment by ZarshaB** [comment]
26>> On clicking on "watch" icon, image flicks and then go to original size.
Video Link = https://www.screencast.com/t/ex4UxGJQ

**Comment by ZarshaB** [comment]
27>> If I enter "e" here then it let me enter so many numbers 🐙 
![image](https://user-images.githubusercontent.com/35685146/37405089-9686ba20-27b5-11e8-896a-e09b4c3ba0c8.png)

**Comment by asifjans** [comment]
(1) 
(3)
(6)
(8)
(9)
(10)
(15)
(17)
(19)
(21)
(22)
(25)
(26)
(27)

**Comment by Anum444** [comment]
Zarsha please test these issues..

1>> It is appearing printed. And when I click on field then it becomes placeholder. (Fixed)
3>> Not aligned. (Fixed)
8>> Please change it's field color to orange. (Fixed)
6>> Anum please put commas as discussed. (FIixed)
9>> It would be ticket for one. (FIXED)
10>> This load icon should be in the middle of page for "Place your Ad" and Order Summary page as it is for other pages.  (FIXED)
15>> Spacing should be same from above and bottom. (Fixed)
17>> Cross icon is not same for all pop ups. It should be same for all pop ups. (Fixed)
19>> Please reduce it's space. (Fixed)
21>> As email field contains label instead of placeholder so when I click on "Login" button without filling fields then it display message "Please enter valid email." Whereas, it should display message "This field is required." (FIXED)
22>> In case of wrong password, it should be:
"Oops!!! Something went wrong.
Please enter correct Username and Password
Forgot Password?" (Fixed)
25>> Headings should have same font black color. (Fixed)
21>> As email field contains label instead of placeholder so when I click on "Login" button without filling fields then it display message "Please enter valid email." Whereas, it should display message "This field is required." (Fixed)
22>> In case of wrong password, it should be: (Fixed)
"Oops!!! Something went wrong.
Please enter correct Username and Password
25>> Headings should have same font black color. (Fixed)
26>> On clicking on "watch" icon, image flicks and then go to original size. (FIXED)

**Comment by ZarshaB** [comment]
**Re-opened**
25>> It's font is different. 
![image](https://user-images.githubusercontent.com/35685146/38090040-cc6543b6-337a-11e8-84b4-b7860b932f74.png)
26

**Comment by ZarshaB** [comment]
27>> Please remove the hover effect for "Sold Out" button.

**Comment by ZarshaB** [comment]
27>> Not fixed

**Comment by Anum444** [comment]
27>> Not fixed  :D **please cache clear krO..**

**Comment by ZarshaB** [comment]
27>> Profile page validations are not same as of Register page.

**Comment by ZarshaB** [comment]
28>> Please change it's label to "WelaDela".
![image](https://user-images.githubusercontent.com/35685146/38488802-f84b0afc-3bfd-11e8-8002-c1b7274df63d.png)

**Comment by asifjans** [comment]
27>> Profile page validations are not same as of Register page. 
Can you please list down, which format is required in fields.

**Comment by ZarshaB** [comment]
27>> Profile page validations are not same as of Register page. 
Can you please list down, which format is required in fields.
**Phone and Passport validation issues.**
