### ISSUE TITLE
Browsers campatibility

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#96]

**Comment by ZarshaB** [comment]
**Mozilla FireFox** 
1) Search box is not appearing correct.
![image](https://user-images.githubusercontent.com/35685146/36414249-7e0b7b3a-1643-11e8-9cde-e4c1c826ba0e.png)

2>> Footer Alignment issue:
![image](https://user-images.githubusercontent.com/35685146/36414344-c8b063a8-1643-11e8-807e-5368984a36fb.png)

3>> Radio buttons are appearing blue.
![image](https://user-images.githubusercontent.com/35685146/36414659-dc81d17c-1644-11e8-8116-659547735333.png)

4>> It allows me to enter alphabets but displays error.
![image](https://user-images.githubusercontent.com/35685146/36414770-3a3101e4-1645-11e8-8efb-87debb61649b.png)

5>> Spacing is not equal.
![image](https://user-images.githubusercontent.com/35685146/36414939-e9d7c588-1645-11e8-958f-b8d353e722b3.png)

6>>

**Comment by ZarshaB** [comment]
I'm unable to go further from this on **Safari and IE.**
![image](https://user-images.githubusercontent.com/35685146/36416939-5ea0d99e-164c-11e8-8bd3-8b356de4c450.png)

**Comment by ZarshaB** [comment]
**IE**
1>> Footer layout issue.
![image](https://user-images.githubusercontent.com/35685146/36418523-ecd9494a-1650-11e8-9191-d2d77917702a.png)

2>> On Contact Us this is appearing on scrolling down.
![image](https://user-images.githubusercontent.com/35685146/36418582-174e6ed0-1651-11e8-93d7-26514b52ca80.png)

3>> Complete figure is not appearing.
![image](https://user-images.githubusercontent.com/35685146/36418685-600460da-1651-11e8-8ef5-640b298fe255.png)

**Comment by Anum444** [comment]
**These issues are Fixed and ready for testing..**

Mozilla FireFox
1>>Search box is not appearing correct. (Fixed)
2>> Footer Alignment issue: (Fixed)
5>> Spacing is not equal. (Fixed)
I'm unable to go further from Home page on Safari and IE. (FIXED)
6>>For safari I'm unable to access any page because it keeps on loading. (FIXED)

IE
1>> Footer layout issue. (Fixed)
2>> On Contact Us this is appearing on scrolling down. (Fixed)
3>> Complete figure is not appearing.
5>> Color changes. (Fixed)
7>> This is appearing on here and Order Summary page also for Billing address and also for Place your Ad. (Fixed)
9>> This page is appearing like this for all images. (Fixed)

**Comment by ZarshaB** [comment]
**Safari Issues**
1>> Search box is appearing like this.
![image](https://user-images.githubusercontent.com/35685146/38136326-15594bd2-3437-11e8-8f5b-658f4ff225c4.png)

**Comment by ZarshaB** [comment]
Reopened
**Safari**
1>> When I click on drop down then after click drop down disappears. Also it's alignment changes when I click.

**Comment by ZarshaB** [comment]
**IE**
8>> It's shape changes when I click on drop down. 
![image](https://user-images.githubusercontent.com/35685146/38418336-6689e27c-39b5-11e8-88c8-ae7739693614.png)

**Comment by Anum444** [comment]
**These issues are Fixed and ready for testing:**

1>> Search box is appearing like this. (Fixed)
3>> This page is appearing like this: (Fixed)
4>> Images of Contact Us are appearing like this: (Fixed)
5>> This is appearing like this. (Fixed)
7>> Labels are not at centre. (Fixed)
1>> When I click on drop down then after click drop down disappears. Also it's alignment changes when I click.
8>> It's shape changes when I click on drop down. (FIXED)
9>> Alignment of "i". (FIXED)

**Comment by ZarshaB** [comment]
**Safari**
8>> Text of banner is moving. Whereas this is fixed for other browsers.

**Comment by ZarshaB** [comment]
**IE**
12>> option is going on next line.
![image](https://user-images.githubusercontent.com/35685146/38500576-45c52b0c-3c24-11e8-92c6-94e8fbeae2cc.png)

**Comment by ZarshaB** [comment]
**Not Fixed**
**Safari**
1>> When I click on drop down then after click drop down disappears. Also it's alignment changes when I click.

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing**
8>> Text of banner(sliders) of Home page is moving. Whereas this is fixed for other browsers. (FIXED)
9>> Value is not in centre. (FIXED)
10>> Alignment of radio buttons. (FIXED)
11>> Alignment of drop downs. (FIXED)
13>> option is going on next line. (FIXED)

**Comment by ZarshaB** [comment]
**Reopened**
10, 13>> It is fixed for View Cars page but not for Car Detail page.

**Comment by ZarshaB** [comment]
**Fire Fox:**

14>> Drop box Alignment changes when it is clicked. 
![image](https://user-images.githubusercontent.com/35685146/38551767-78057324-3cd3-11e8-9531-8eaf6a509d38.png)

**Comment by Anum444** [comment]
6>> This is not taking to "Our Featured Cars" section after login and also when it is moved from empty cart on clicking on "Continue" button. (Fixed)
10>> Alignment of radio buttons. (Fixed)
13>> option is going on next line. (Fixed)

**Comment by ZarshaB** [comment]
**Safari**
9>> When I click on any price from drop down then it does not get selected and I have to click somewhere else to and then value appears in drop down and also value appears in the corner of drop down.
![image](https://user-images.githubusercontent.com/35685146/38558704-61ba1874-3cea-11e8-98d4-30946922cff5.png)
![image](https://user-images.githubusercontent.com/35685146/38558734-7409c3b2-3cea-11e8-8825-fbd9112bec35.png)

**Comment by Anum444** [comment]
Fixed
9>> When I click on any price from drop down then it does not get selected and I have to click somewhere else to and then value appears in drop down and also value appears in the corner of drop down.

**Comment by ZarshaB** [comment]
**IE**

7>> This is appearing on Order Summary page.**(Not Fixed)**
![image](https://user-images.githubusercontent.com/35685146/38816190-fd98694e-41ae-11e8-9ad4-c4a8758099c3.png)

**Comment by Anum444** [comment]
IE

7>> This is appearing on Order Summary page.  **(Fixed)**
