### ISSUE TITLE
Client's Feedback 23-02-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/Inovedia#98]

**Comment by ZarshaB** [comment]
Rectifications Pending from Sprint 1
1.	Please reduce the size of Inovedia Technologies at the bottom.
2.	All the prices while uploading ad or at the time of viewing should be without decimals.
3.	In order summary page, there must be Point redeem button after subtotal for discount.

**Comment by ZarshaB** [comment]
Rectifications Required after Review
1.	Not able to create account using my Hotmail ID as I’m not getting the verification email on it.
2.	Spelling of favorites all across the website should be “Favorites”.
3.	Once the action has been taken by the customer on all links sent to their email addresses (e.g. Password reset link, Account activation link etc), the link should become inactive.
4.	In returning customer, when wrong email is entered, then message should read “Please enter a valid e-mail address.
5.	For signing-in with facebook, please use following. Login should be written together: -
![image](https://user-images.githubusercontent.com/35685146/36585618-6b3ff09e-18a0-11e8-8a33-11525f24679c.png)

**Comment by ZarshaB** [comment]
6.	On “Register Account” Page, the message should read: If you already have an account with us, please login here. (hyperlink)
7.	On “Register Account” Page, the error messages are not correct. Where data in field is incorrect, then it should convey “The information provided is not valid” and if the mandatory field is left empty, then the message should read “This field is mandatory”.
8.	For all mandatory fields in whole website, when data in field is incorrect, then it should convey “The information provided is not valid” and if the mandatory field is left empty, then the message should read “This field is mandatory”.
9.	DOB: The empty tab should display DD/MM/YYYY which will convey the right format to the customer. Additionally, in calendar, there is no option for the customer to select his birth year.
10.	Passport section is not taking alphabets. It should accept only numbers and alphabets.
11.	In Hear About Us, the option should be “Social Media” instead of Social.
12.	In all of the website, letter “Z” has a line in it. Please rectify it and make it a normal “Z”.
13.	Captcha should be below the Notification Consent and T&Cs checkboxes and Register button should be aligned towards right with this Captcha and should be double the current size.
14.	When customer presses “register button” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.” 
15.	In verification email, Exclamation mark (!!!) are missing in We’ve been waiting for you.
16.	Resend Verification email did not work. I tried 2-3 times but did not get the email.
17.	When customer logs-in, it should land on the page from where he routed to log-in page. In certain cases, it landed on the homepage.

**Comment by ZarshaB** [comment]
18.	Upload Ad:-
•	In mileage, up-down arrow should be removed.
•	Customer should have option to remove image.
•	Make all fields mandatory.
•	Where customer has to manually enter data like mileage, ad title and description, the error message should read “This field is mandatory.”
•	When “images” tab is clicked, it lands on the bottom of that page. Please rectify it.
•	When “save” button is clicked without checking terms and conditions checkbox, the error message has an extra “comma” after word “conditions”. Please remove it.
•	When customer presses “save” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.” 
•	Ad was not saved
•	Uploading Mulkiya Copy option is required.

19.	In order summary page, When customer presses “continue” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.” 
20.	In How it works, when customer presses learn more of clicks on HOW it Works, then it should be routed to the page and should stay there for 1.5-2 seconds and then video should start playing in full screen. Currently, when I go to that page, only 20% video is visible and its hard to find the play bar.

**Comment by ZarshaB** [comment]
FAQs
•	In General, One question “what is the price of a ticket” is missing.
•	In General, “what if the car fails to pass the test” question, there are two extra commas after “Only then” and “In case”. Please remove these commas
•	In Seller question “ Why Mulkiya is required”, please rephrase the answer as “Unlike other portals, we consider every car as our own and put in best efforts to ensure the sale. We’ll also the market your car free of cost and will be devoting time, effort and money to achieve the goal. Therefore, we require a mulkiya/ownership document to ascertain the ownership of the car and to ensure that only valid cars are listed on our website.
•	In Seller question, ”When I am uploading the ad,” please rephrase the question as “When I post the ad of my car, do I get to decide the price of the car? And rephrase the answer as Yes. You will be the one who will decide on the price. WelaDela ensures that you get desired price for your car. We’ll assist you in the process and will ensure that the price is in line with the current market value of the car.
•	In seller question, “I’m a seller, the draw of my car”, please rephrase the answer as Once the draw is conducted and winner is announced, we will contact the seller through the information provided to us. After that, you’ll have to send us passing report copy for car fitness test from any of the Government recognized testing facilities in order to save time. Once we receive the fitness certificate copy, we will request you to meet at any of the transfer facilities for finalizing the transaction.
•	In Buyer, add “folder” after Junk email.
•	In Buyer, rephrase the question 2 as “How secure is the transaction made online?”
•	In Buyer, please rephrase the answer to question 2 as Your transactions are very secure. Our website uses a payment gateway that ensures that all payments are safeguarded by keeping the strictest processes and systems in place.
•	In Buyer, Please rephrase the third last question as How can I claim the prize in case I am out of country?
•	In Buyer, please rephrase the second last question as Can I still enter the draw even if I’m a non-resident of UAE?

**Comment by ZarshaB** [comment]
22.	Points Redeem Policy
•	HyperLink in 1.1, Contact Us in 6.1 and 6.2 are opening in same tab. It should open in a separate tab like T&Cs in this section is opening.
•	Hyperlink in 11 should open compose email in outlook.

**Comment by ZarshaB** [comment]
23.	Privacy Policy

•	Terms and Conditions have been uploaded in this section. Please replace it with privacy policy document that have been provided to you.

**Comment by ZarshaB** [comment]
24.	Contact Us

•	Error message on all the fields when data in field is incorrect should convey “The information provided is not valid” OR “Please enter a valid e-mail address” and if the mandatory field is left empty, then the message should read “This field is mandatory”.
•	When customer sends an email to info@weladela.com, then he should get the same email as he got by submitting enquiry form.
•	When Inquiry form is submitted, the email I got was cut from side. Pasted below for your reference. I received this email on Hotmail ID. Please check if this issue has to do something with Hotmail as I made account from my gmail and getting proper emails on it.

**Comment by ZarshaB** [comment]
25.	Car View

•	In search filters, please refer to Warranty and Service History. I can opt for all the options at the same time. This should not be happening. At any given time, I should be able to select only one option e.g. In service history, I should either opt Yes or No or Does Not apply.
•	When I add any car in My favorites, the message should read “The listing has been added to your favorites.”
•	When the car has been added to your favorites, Heart Icon on that particular car should turn to orange and should remain orange until it is removed from favorite. When customer again clicks on that orange icon, it should be removed from favorites, icon should return to normal and message should read: “The listing has been removed from your favorites.”
•	When viewing cars, I don’t have option to slide the pictures. Please add arrows on sides for scrolling.

**Comment by ZarshaB** [comment]
26.	My Favorites

•	For the cars added in My Favorites, Ad title of the car should be hyperlink and when clicked should take you to the that particular ad and should open in a separate tab.
•	When customer clicks on delete button, then it should display message: “Are you sure you want to remove this listing from your favorites?”
•	When car is deleted, it is not displaying any message. The message should read “The listing has been removed from your favorites.”

**Comment by ZarshaB** [comment]
27.	Forgot Password

•	The error message for invalid email should read “Please enter a valid email.”
•	When email entered and reset password button is pressed, then the message should read “We're here to help. Password reset link has been sent to your email address -------@xyz.com.”

**Comment by ZarshaB** [comment]
28.	Password Reset

•	When the customer has successfully reset his password, then the following message should display “Your password has been reset and it works like a charm!!!”
•	Customer should also get a confirmation email once the password has been reset. Template below:-

**Comment by ZarshaB** [comment]
29.	Account Delete

•	Customer should have option of deleting his account at the bottom in My Profile. 
•	When customer clicks the button, it should display the pop-up message with two buttons at the bottom: - 
We’re really sad to see you go!!!
Do you really want to break-up with us?
Let’s stay Together(For Cancel Button)                Delete Account (for Account deletion)
•	When customer has confirmed the account deletion, it should display the pop-up message. 
We hate goodbyes!!!
But we respect your decision and have deleted your account. However, whenever you want to feel special and lucky, just let us know here(hyperlink for account registration) and we will welcome you with arms wide open. 
30.	New Customer Text on Login/Register Page

•	The text on New Customer section on Login/Register Page will read as follows:-

Now We’re Talking!!!

By creating an account, you will be able to feel special, very very special

**Comment by ZarshaB** [comment]
Rectifications Discussed during Last Demo:-
	New Customer on Login/Register Page:-
1.	Submit Message Inquiry
2.	Wrong Email Scenario
3.	Exclamation Mark and additional fullstop
4.	Favorites Spellings
My Favorites: 
1.	Ticket Price
2.	Remove from Favorites Spelling
My Ads: 
1.	When status of car is sold, then Delete button should be inactive
Others: 
1.	Remove decimals from all prices
2.	Ticket should be in printable size 
3.	Watermarking on ticket required

**Comment by ZarshaB** [comment]
**Social media links:**
Facebook = https://www.facebook.com/WelaDelacom-406885159725894/?ref=bookmarks 
Youtube = https://www.youtube.com/channel/UCHaFNwVwypnxNbfZPR3iRrA?view_as=subscriber
Instagram = https://www.instagram.com/wela_dela/

**Comment by ZarshaB** [comment]
**Docs**
[Email Template to Successfull Seller.docx](https://github.com/asifjans/Inovedia/files/1751040/Email.Template.to.Successfull.Seller.docx)
[Price Denomination.docx](https://github.com/asifjans/Inovedia/files/1751041/Price.Denomination.docx)
[Rectifications.docx](https://github.com/asifjans/Inovedia/files/1751042/Rectifications.docx)
[Ticket Refund Content.docx](https://github.com/asifjans/Inovedia/files/1751043/Ticket.Refund.Content.docx)
[Ticket Transfer Content.docx](https://github.com/asifjans/Inovedia/files/1751044/Ticket.Transfer.Content.docx)
[Winner Email Template.docx](https://github.com/asifjans/Inovedia/files/1751045/Winner.Email.Template.docx)

**Comment by ZarshaB** [comment]
Privacy Policy Document = 
[Privacy Policy.docx](https://github.com/asifjans/Inovedia/files/1751053/Privacy.Policy.docx)

**Comment by Anum444** [comment]
** (From Client Feed Back) These issues are fixed and ready for testing:**

1.2: All the prices while uploading ad or at the time of viewing should be without decimals.  (Fixed)
2: Spelling of favorites all across the website should be “Favorites”.  (Fixed)
3: In order summary page, there must be Point redeem button after subtotal for discount. (Fixed)
When customer logs-in, it should land on the page from where he routed to log-in page. In certain cases, it landed on the homepage. (Fixed)
4: In returning customer, when wrong email is entered, then message should read “Please enter a valid e-mail address.  (Fixed)
6: On “Register Account” Page, the message should read: If you already have an account with us, please login here. (hyperlink) .  (Fixed)
10: Passport section is not taking alphabets. It should accept only numbers and alphabets. (Fixed)
11 : In Hear About Us, the option should be “Social Media” instead of Social. (Fixed)
13: Captcha should be below the Notification Consent and T&Cs checkboxes and Register button should be aligned towards right with this Captcha and should be double the current size. (Fixed)
14: When customer presses “register button” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.” (Fixed)
15: In verification email, Exclamation mark (!!!) are missing in We’ve been waiting for you. (Fixed)
18: Upload Ad:-  (Fixed)

•	In mileage, up-down arrow should be removed.
•	Customer should have option to remove image.
•	Make all fields mandatory.
•	Where customer has to manually enter data like mileage, ad title and description, the error message should read “This field is mandatory.”
•	When “images” tab is clicked, it lands on the bottom of that page. Please rectify it.
•	When “save” button is clicked without checking terms and conditions checkbox, the error message has an extra “comma” after word “conditions”. Please remove it.
•	When customer presses “save” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.”
•	Ad was not saved
•	Uploading Mulkiya Copy option is required.
19: In order summary page, When customer presses “continue” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.” (Fixed)
21: FAQs (fixed)
22: Points Redeem Policy (Fixed)
•	HyperLink in 1.1, Contact Us in 6.1 and 6.2 are opening in same tab. It should open in a separate tab like T&Cs in this section is opening.
•	Hyperlink in 11 should open compose email in outlook.
23: •	Terms and Conditions have been uploaded in this section. Please replace it with privacy policy document that have been provided to you. (Fixed) 
25.Car View (Fixed)
• In search filters, please refer to Warranty and Service History. I can opt for all the options at the same time. This should not be happening. At any given time, I should be able to select only one option e.g. In service history, I should either opt Yes or No or Does Not apply. (Fixed)

• When I add any car in My favorites, the message should read “The listing has been added to your favorites.” (Fixed)
• When the car has been added to your favorites, Heart Icon on that particular car should turn to orange and should remain orange until it is removed from favorite. When customer again clicks on that orange icon, it should be removed from favorites, icon should return to normal and message should read: “The listing has been removed from your favorites.” (Fixed)
• When viewing cars, I don’t have option to slide the pictures. Please add arrows on sides for scrolling.(Fixed)
27: Forgot Password
•	The error message for invalid email should read “Please enter a valid email.”
•	When email entered and reset password button is pressed, then the message should read “We're here to help. Password reset link has been sent to your email address -------@xyz.com.” (Fixed)
30: New Customer Text on Login/Register Page
•	The text on New Customer section on Login/Register Page will read as follows:- (Fixed)
31: Social links add (Fixed)

**Comment by ZarshaB** [comment]
**Not Fixed:**
2>> The word "Favorites" is changes in message. But Label of icon is not changed. Please change the label everywhere in pop up, View cars, Car detail page.
![image](https://user-images.githubusercontent.com/35685146/36658739-c70e4254-1af3-11e8-95ea-073c6f86414c.png)

30>> Content is changed. Please put a full stop at the end of message. 
![image](https://user-images.githubusercontent.com/35685146/36658919-733ba828-1af4-11e8-86aa-5d70424f6ba4.png)

27>> Please change  message to "Please enter a valid email." 
![image](https://user-images.githubusercontent.com/35685146/36659244-99ef1080-1af5-11e8-9a47-3fdb0f9bf3da.png)

There would be full stop after message.
![image](https://user-images.githubusercontent.com/35685146/36659262-b2a6f3ae-1af5-11e8-8282-ecec37a7b8d9.png)

25>> Arrows are not working.
![image](https://user-images.githubusercontent.com/35685146/36659440-4a65af64-1af6-11e8-875c-49dd0f95316e.png)

21>> He asked to remove double commas. Single comma will come at the highlighted places.
![image](https://user-images.githubusercontent.com/35685146/36659705-281151ba-1af7-11e8-891a-607c0b0ca1ad.png)

Please remove this highlighted extra text and replace it with "Once we receive the fitness certificate copy, we will request you to meet at any of the transfer facilities for finalizing the transaction." 
as mentioned.

![image](https://user-images.githubusercontent.com/35685146/36660030-6828e41a-1af8-11e8-9d59-0217554bde96.png)

18>>In mileage, up-down arrow are not removed.
The cross icon the visible as broken image.
![image](https://user-images.githubusercontent.com/35685146/36660382-c620b7cc-1af9-11e8-9a84-19088e824658.png)

All fields are not mandatory.
	Where customer has to manually enter data like mileage, ad title and description, the error message should read “This field is mandatory.”
•	When “images” tab is clicked, it lands on the bottom of that page. Please rectify it.
•	When “save” button is clicked without checking terms and conditions checkbox, the error message has an extra “comma” after word “conditions”. Please remove it.
•	When customer presses “save” without checking the T&Cs checkbox, the message should read “Please check the "terms and conditions" to continue.”

14, 15 >> To check these I have to click on "Register" button but button is not clickable.

13>> It's not double the current size.
10>> It should only accept numbers and alphabets. It is also accepting things other than number and alphabets.
![image](https://user-images.githubusercontent.com/35685146/36661135-44b0abea-1afc-11e8-910b-6cd4ef6add8f.png)

4>> This message should only be displayed if I enter wrong email address. As it is giving me error for correct email address also.
![image](https://user-images.githubusercontent.com/35685146/36661342-d0f43d60-1afc-11e8-95ea-aa8cb37358e8.png)

**Comment by Anum444** [comment]
**These issues are fixed and ready for testing:**

**Zarsha's New Feedback:** 

2>> The word "Favorites" is changes in message. But Label of icon is not changed. Please change the label everywhere in pop up, View cars, Car detail page. And also from message pop of My favorites.
30>> Content is changed. Please put a full stop at the end of message.
27>> Please change message to "Please enter a valid email."
There would be full stop after message.
21>> He asked to remove double commas. Single comma will come at the highlighted places. 
18>>In mileage, up-down arrow are not removed.
The cross icon the visible as broken image.
14, 15 >> To check these I have to click on "Register" button but button is not clickable. 
13>> It's not double the current size.
10>> It should only accept numbers and alphabets. It is also accepting things other than number and alphabets. 

**Client FeedBack:**
1.1: Please reduce the size of Inovedia Technologies at the bottom. 
1.2: All the prices while uploading ad or at the time of viewing should be without decimals. 
5: For signing-in with facebook, please use following. Login should be written together: -
7: On “Register Account” Page, the error messages are not correct. Where data in field is incorrect, then it should convey “The information provided is not valid” and if the mandatory field is left empty, then the message should read “This field is mandatory”.
8: For all mandatory fields in whole website, when data in field is incorrect, then it should convey “The information provided is not valid” and if the mandatory field is left empty, then the message should read “This field is mandatory”.
9: DOB: The empty tab should display DD/MM/YYYY which will convey the right format to the customer. Additionally, in calendar, there is no option for the customer to select his birth year. (Anum_Fixed)
26: •	For the cars added in My Favorites, Ad title of the car should be hyperlink and when clicked should take you to the that particular ad and should open in a separate tab.
•	When customer clicks on delete button, then it should display message: “Are you sure you want to remove this listing from your favorites?”
•	When car is deleted, it is not displaying any message. The message should read “The listing has been removed from your favorites.”

27: •	The error message for invalid email should read “Please enter a valid email.”
•	When email entered and reset password button is pressed, then the message should read “We're here to help. Password reset link has been sent to your email address -------@xyz.com.”
29: Account Delete

**Comment by ZarshaB** [comment]
**Not Fixed**
2>> I can still see incorrect spelling in pop up.
![image](https://user-images.githubusercontent.com/35685146/36716779-565862ae-1bbd-11e8-8375-64abc350e56d.png)

27>> Please put full stop at the end of message.
![image](https://user-images.githubusercontent.com/35685146/36717447-fa5b1476-1bbf-11e8-9295-f0e39364107b.png)

21>> There should be same space as we have for "After that...." after full stop.
![image](https://user-images.githubusercontent.com/35685146/36717668-cb09335a-1bc0-11e8-8f50-df7c5a7082b4.png)

**Comment by ZarshaB** [comment]
7>> Please also change these highlighted fields to "The information provided is not valid”.
![image](https://user-images.githubusercontent.com/35685146/36724886-6232ef54-1bd6-11e8-8335-c0eaa3f32b2e.png)

**Comment by ZarshaB** [comment]
8>> Please change these messages to "This field is mandatory."
![image](https://user-images.githubusercontent.com/35685146/36725091-01b4c494-1bd7-11e8-8f06-51d26227b723.png)
![image](https://user-images.githubusercontent.com/35685146/36725099-0933364c-1bd7-11e8-93e9-a18d59a4b46c.png)
![image](https://user-images.githubusercontent.com/35685146/36725116-113ef718-1bd7-11e8-851e-e2b90d9e335c.png)

**Comment by ZarshaB** [comment]
29>> Please check highlighted spaces with other messages. These are not same.
![image](https://user-images.githubusercontent.com/35685146/36725180-490efada-1bd7-11e8-82a4-57476a5ae389.png)

**Comment by ZarshaB** [comment]
17>> For Place your Ad, When I click on button without login then it redirected me to login page but didn't display me error message that we used to display on login page. And after login it redirected me to Home page.
Same is the case with cart.
If I click on Favorite icon from pop up then instead of as we do before that after login it redirects to detail page of that ad now it redirects to same page.
And  messages that we displayed before are not being displayed now on Login page in these cases.
And also on clicking on Buy Ticket instead of redirecting it to Order summary page after login it redirects to Car detail page.

**Comment by ZarshaB** [comment]
2>> It is not fixed as I tried again those links and it worked for me.

**Comment by ZarshaB** [comment]
Please also change it's message to "This field is mandatory."
![image](https://user-images.githubusercontent.com/35685146/36777851-c94f8ad8-1c8c-11e8-948c-bb7cfdfdce82.png)

**Comment by ZarshaB** [comment]
The ticket was having watermark but now I can't see it.
![image](https://user-images.githubusercontent.com/35685146/36777929-0b9b8784-1c8d-11e8-8080-82a605d536b6.png)

**Comment by ZarshaB** [comment]
Prices are appearing in decimal. And also alignment issue for discount, order id and date.
![image](https://user-images.githubusercontent.com/35685146/36739169-1dcba632-1c01-11e8-82a8-8c64ea0ff999.png)

**Comment by ZarshaB** [comment]
When customer sends an email to info@weladela.com, then he should get the same email as he got by submitting enquiry form.

**Comment by ZarshaB** [comment]
It would be according to page.
![image](https://user-images.githubusercontent.com/35685146/36782391-a57e160c-1c9a-11e8-8286-4e429a1bc27c.png)

**Comment by asifjans** [comment]
3>>**(Fixed)** Please also change it's message to "This field is mandatory."
![image](https://user-images.githubusercontent.com/35685146/36777851-c94f8ad8-1c8c-11e8-948c-bb7cfdfdce82.png)

**Comment by ZarshaB** [comment]
Not Fixed:
5>> Decimal is there in price.
![image](https://user-images.githubusercontent.com/35685146/36833485-533e0048-1d51-11e8-82a6-d846d9199a49.png)

**Comment by asifjans** [comment]
(5) Fixed
